<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * The class to handle Vietnam Provinces
 *
 * @author   htdat
 * @since    1.0
 *
 */
class WooViet_Provinces {

	/**
	 * Constructor: Add filters
	 */
	public function __construct() {
		add_filter( 'woocommerce_states', array( $this, 'add_provinces' ) );
		add_filter( 'woocommerce_get_country_locale', array( $this, 'edit_vn_locale' ) );
		add_filter( 'woocommerce_localisation_address_formats', array( $this, 'edit_vn_address_formats' ) );

		// Enqueue province scripts
		// add_action( 'wp_enqueue_scripts', array( $this, 'load_provinces_scripts' ) );
	}

	/**
	 * Change the address format of Vietnam, add {state} (or "Province" in Vietnam)
	 *
	 * @param $array
	 *
	 * @return array
	 */
	public function edit_vn_address_formats( $array ) {

		$array['VN'] = "{name}\n{company}\n{address_1}\n{city}\n{state}\n{country}";

		return $array;

	}

	/**
	 * Change the way displaying address fields in the checkout page when selecting Vietnam
	 *
	 * @param $array
	 *
	 * @return array
	 */
	public function edit_vn_locale( $array ) {
		$array['VN']['state']['label']    = __( 'Province', 'woo-viet' );
		$array['VN']['state']['required'] = true;

		$array['VN']['city']['label']      = __( 'District', 'woo-viet' );
		$array['VN']['postcode']['hidden'] = true;

		return $array;
	}


	/**
	 * Add 63 provinces of Vietnam
	 *
	 * @param $states
	 *
	 * @return array
	 */
	public function add_provinces( $states ) {
		/**
		 * @source: https://vi.wikipedia.org/wiki/Tỉnh_thành_Việt_Nam and https://en.wikipedia.org/wiki/Provinces_of_Vietnam
		 */
		$states['VN'] = array(
			'AN-GIANG'        => __( 'An Giang', 'woo-viet' ),
			'BA-RIA-VUNG-TAU' => __( 'Ba Ria - Vung Tau', 'woo-viet' ),
			'BAC-LIEU'        => __( 'Bac Lieu', 'woo-viet' ),
			'BAC-KAN'         => __( 'Bac Kan', 'woo-viet' ),
			'BAC-GIANG'       => __( 'Bac Giang', 'woo-viet' ),
			'BAC-NINH'        => __( 'Bac Ninh', 'woo-viet' ),
			'BEN-TRE'         => __( 'Ben Tre', 'woo-viet' ),
			'BINH-DUONG'      => __( 'Binh Duong', 'woo-viet' ),
			'BINH-DINH'       => __( 'Binh Dinh', 'woo-viet' ),
			'BINH-PHUOC'      => __( 'Binh Phuoc', 'woo-viet' ),
			'BINH-THUAN'      => __( 'Binh Thuan', 'woo-viet' ),
			'CA-MAU'          => __( 'Ca Mau', 'woo-viet' ),
			'CAO-BANG'        => __( 'Cao Bang', 'woo-viet' ),
			'CAN-THO'         => __( 'Can Tho', 'woo-viet' ),
			'DA-NANG'         => __( 'Da Nang', 'woo-viet' ),
			'DAK-LAK'         => __( 'Dak Lak', 'woo-viet' ),
			'DAK-NONG'        => __( 'Dak Nong', 'woo-viet' ),
			'DONG-NAI'        => __( 'Dong Nai', 'woo-viet' ),
			'DONG-THAP'       => __( 'Dong Thap', 'woo-viet' ),
			'DIEN-BIEN'       => __( 'Dien Bien', 'woo-viet' ),
			'GIA-LAI'         => __( 'Gia Lai', 'woo-viet' ),
			'HA-GIANG'        => __( 'Ha Giang', 'woo-viet' ),
			'HA-NAM'          => __( 'Ha Nam', 'woo-viet' ),
			'HA-NOI'          => __( 'Ha Noi', 'woo-viet' ),
			'HA-TINH'         => __( 'Ha Tinh', 'woo-viet' ),
			'HAI-DUONG'       => __( 'Hai Duong', 'woo-viet' ),
			'HAI-PHONG'       => __( 'Hai Phong', 'woo-viet' ),
			'HOA-BINH'        => __( 'Hoa Binh', 'woo-viet' ),
			'HAU-GIANG'       => __( 'Hau Giang', 'woo-viet' ),
			'HUNG-YEN'        => __( 'Hung Yen', 'woo-viet' ),
			'HO-CHI-MINH'     => __( 'Ho Chi Minh', 'woo-viet' ),
			'KHANH-HOA'       => __( 'Khanh Hoa', 'woo-viet' ),
			'KIEN-GIANG'      => __( 'Kien Giang', 'woo-viet' ),
			'KON-TUM'         => __( 'Kon Tum', 'woo-viet' ),
			'LAI-CHAU'        => __( 'Lai Chau', 'woo-viet' ),
			'LAO-CAI'         => __( 'Lao Cai', 'woo-viet' ),
			'LANG-SON'        => __( 'Lang Son', 'woo-viet' ),
			'LAM-DONG'        => __( 'Lam Dong', 'woo-viet' ),
			'LONG-AN'         => __( 'Long An', 'woo-viet' ),
			'NAM-DINH'        => __( 'Nam Dinh', 'woo-viet' ),
			'NGHE-AN'         => __( 'Nghe An', 'woo-viet' ),
			'NINH-BINH'       => __( 'Ninh Binh', 'woo-viet' ),
			'NINH-THUAN'      => __( 'Ninh Thuan', 'woo-viet' ),
			'PHU-THO'         => __( 'Phu Tho', 'woo-viet' ),
			'PHU-YEN'         => __( 'Phu Yen', 'woo-viet' ),
			'QUANG-BINH'      => __( 'Quang Binh', 'woo-viet' ),
			'QUANG-NAM'       => __( 'Quang Nam', 'woo-viet' ),
			'QUANG-NGAI'      => __( 'Quang Ngai', 'woo-viet' ),
			'QUANG-NINH'      => __( 'Quang Ninh', 'woo-viet' ),
			'QUANG-TRI'       => __( 'Quang Tri', 'woo-viet' ),
			'SOC-TRANG'       => __( 'Soc Trang', 'woo-viet' ),
			'SON-LA'          => __( 'Son La', 'woo-viet' ),
			'TAY-NINH'        => __( 'Tay Ninh', 'woo-viet' ),
			'THAI-BINH'       => __( 'Thai Binh', 'woo-viet' ),
			'THAI-NGUYEN'     => __( 'Thai Nguyen', 'woo-viet' ),
			'THANH-HOA'       => __( 'Thanh Hoa', 'woo-viet' ),
			'THUA-THIEN-HUE'  => __( 'Thua Thien Hue', 'woo-viet' ),
			'TIEN-GIANG'      => __( 'Tien Giang', 'woo-viet' ),
			'TRA-VINH'        => __( 'Tra Vinh', 'woo-viet' ),
			'TUYEN-QUANG'     => __( 'Tuyen Quang', 'woo-viet' ),
			'VINH-LONG'       => __( 'Vinh Long', 'woo-viet' ),
			'VINH-PHUC'       => __( 'Vinh Phuc', 'woo-viet' ),
			'YEN-BAI'         => __( 'Yen Bai', 'woo-viet' ),
		);
		
		$this->create_VN_state();
		// $states['VN'] = $this->create_VN_state();
		return $states;

	}
	public function create_VN_state(){
		$list_provinces = $this->list_VN_provinces();
		$list_cities = $this->list_VN_cities();
		$vn_states = [];
		foreach ($list_cities as $lkey => $cities){
			foreach ($cities as $key => $city){
				$vn_states["$lkey--$key"] = "{$list_provinces[$lkey]} - $city";
			}
		}
		return $vn_states;
	}
	public function list_VN_provinces(){
		return  array(
			'AN-GIANG'        => __( 'An Giang', 'bbs' ),
			'BA-RIA-VUNG-TAU' => __( 'Ba Ria - Vung Tau', 'bbs' ),
			'BAC-LIEU'        => __( 'Bac Lieu', 'bbs' ),
			'BAC-KAN'         => __( 'Bac Kan', 'bbs' ),
			'BAC-GIANG'       => __( 'Bac Giang', 'bbs' ),
			'BAC-NINH'        => __( 'Bac Ninh', 'bbs' ),
			'BEN-TRE'         => __( 'Ben Tre', 'bbs' ),
			'BINH-DUONG'      => __( 'Binh Duong', 'bbs' ),
			'BINH-DINH'       => __( 'Binh Dinh', 'bbs' ),
			'BINH-PHUOC'      => __( 'Binh Phuoc', 'bbs' ),
			'BINH-THUAN'      => __( 'Binh Thuan', 'bbs' ),
			'CA-MAU'          => __( 'Ca Mau', 'bbs' ),
			'CAO-BANG'        => __( 'Cao Bang', 'bbs' ),
			'CAN-THO'         => __( 'Can Tho', 'bbs' ),
			'DA-NANG'         => __( 'Da Nang', 'bbs' ),
			'DAK-LAK'         => __( 'Dak Lak', 'bbs' ),
			'DAK-NONG'        => __( 'Dak Nong', 'bbs' ),
			'DONG-NAI'        => __( 'Dong Nai', 'bbs' ),
			'DONG-THAP'       => __( 'Dong Thap', 'bbs' ),
			'DIEN-BIEN'       => __( 'Dien Bien', 'bbs' ),
			'GIA-LAI'         => __( 'Gia Lai', 'bbs' ),
			'HA-GIANG'        => __( 'Ha Giang', 'bbs' ),
			'HA-NAM'          => __( 'Ha Nam', 'bbs' ),
			'HA-NOI'          => __( 'Ha Noi', 'bbs' ),
			'HA-TINH'         => __( 'Ha Tinh', 'bbs' ),
			'HAI-DUONG'       => __( 'Hai Duong', 'bbs' ),
			'HAI-PHONG'       => __( 'Hai Phong', 'bbs' ),
			'HOA-BINH'        => __( 'Hoa Binh', 'bbs' ),
			'HAU-GIANG'       => __( 'Hau Giang', 'bbs' ),
			'HUNG-YEN'        => __( 'Hung Yen', 'bbs' ),
			'HO-CHI-MINH'     => __( 'Ho Chi Minh', 'bbs' ),
			'KHANH-HOA'       => __( 'Khanh Hoa', 'bbs' ),
			'KIEN-GIANG'      => __( 'Kien Giang', 'bbs' ),
			'KON-TUM'         => __( 'Kon Tum', 'bbs' ),
			'LAI-CHAU'        => __( 'Lai Chau', 'bbs' ),
			'LAO-CAI'         => __( 'Lao Cai', 'bbs' ),
			'LANG-SON'        => __( 'Lang Son', 'bbs' ),
			'LAM-DONG'        => __( 'Lam Dong', 'bbs' ),
			'LONG-AN'         => __( 'Long An', 'bbs' ),
			'NAM-DINH'        => __( 'Nam Dinh', 'bbs' ),
			'NGHE-AN'         => __( 'Nghe An', 'bbs' ),
			'NINH-BINH'       => __( 'Ninh Binh', 'bbs' ),
			'NINH-THUAN'      => __( 'Ninh Thuan', 'bbs' ),
			'PHU-THO'         => __( 'Phu Tho', 'bbs' ),
			'PHU-YEN'         => __( 'Phu Yen', 'bbs' ),
			'QUANG-BINH'      => __( 'Quang Binh', 'bbs' ),
			'QUANG-NAM'       => __( 'Quang Nam', 'bbs' ),
			'QUANG-NGAI'      => __( 'Quang Ngai', 'bbs' ),
			'QUANG-NINH'      => __( 'Quang Ninh', 'bbs' ),
			'QUANG-TRI'       => __( 'Quang Tri', 'bbs' ),
			'SOC-TRANG'       => __( 'Soc Trang', 'bbs' ),
			'SON-LA'          => __( 'Son La', 'bbs' ),
			'TAY-NINH'        => __( 'Tay Ninh', 'bbs' ),
			'THAI-BINH'       => __( 'Thai Binh', 'bbs' ),
			'THAI-NGUYEN'     => __( 'Thai Nguyen', 'bbs' ),
			'THANH-HOA'       => __( 'Thanh Hoa', 'bbs' ),
			'THUA-THIEN-HUE'  => __( 'Thua Thien - Hue', 'bbs' ),
			'TIEN-GIANG'      => __( 'Tien Giang', 'bbs' ),
			'TRA-VINH'        => __( 'Tra Vinh', 'bbs' ),
			'TUYEN-QUANG'     => __( 'Tuyen Quang', 'bbs' ),
			'VINH-LONG'       => __( 'Vinh Long', 'bbs' ),
			'VINH-PHUC'       => __( 'Vinh Phuc', 'bbs' ),
			'YEN-BAI'         => __( 'Yen Bai', 'bbs' ),
		);
	}
	public function list_VN_cities(){
		return array(
			'AN-GIANG' => array(
				'huyen-an-phu' => 'Huyện An Phú',
				'thanh-pho-chau-doc' => 'Thành phố Châu Đốc',
				'huyen-chau-phu' => 'Huyện Châu Phú',
				'huyen-chau-thanh' => 'Huyện Châu Thành',
				'huyen-cho-moi' => 'Huyện Chợ Mới',
				'thanh-pho-long-xuyen' => 'Thành phố Long Xuyên',
				'huyen-phu-tan' => 'Huyện Phú Tân',
				'thi-xa-tan-chau' => 'Thị xã Tân Châu',
				'huyen-thoai-son' => 'Huyện Thoại Sơn',
				'huyen-tinh-bien' => 'Huyện Tịnh Biên',
				'huyen-tri-ton' => 'Huyện Tri Tôn',
			),
			'BA-RIA-VUNG-TAU' => array(
				'thanh-pho-ba-ria' => 'Thành phố Bà Rịa',
				'huyen-chau-duc' => 'Huyện Châu Đức',
				'huyen-con-dao' => 'Huyện Côn Đảo',
				'huyen-dat-do' => 'Huyện Đất Đỏ',
				'huyen-long-dien' => 'Huyện Long Điền',
				'thi-xa-phu-my' => 'Thị xã Phú Mỹ',
				'thanh-pho-vung-tau' => 'Thành phố Vũng Tàu',
				'huyen-xuyen-moc' => 'Huyện Xuyên Mộc',
			),
			'BAC-GIANG' => array(
				'thanh-pho-bac-giang' => 'Thành phố Bắc Giang',
				'huyen-hiep-hoa' => 'Huyện Hiệp Hòa',
				'huyen-lang-giang' => 'Huyện Lạng Giang',
				'huyen-luc-nam' => 'Huyện Lục Nam',
				'huyen-luc-ngan' => 'Huyện Lục Ngạn',
				'huyen-son-dong' => 'Huyện Sơn Động',
				'huyen-tan-yen' => 'Huyện Tân Yên',
				'huyen-viet-yen' => 'Huyện Việt Yên',
				'huyen-yen-dung' => 'Huyện Yên Dũng',
				'huyen-yen-the' => 'Huyện Yên Thế',
			),
			'BAC-KAN' => array(
				'huyen-ba-be' => 'Huyện Ba Bể',
				'thanh-pho-bac-kan' => 'Thành Phố Bắc Kạn',
				'huyen-bach-thong' => 'Huyện Bạch Thông',
				'huyen-cho-don' => 'Huyện Chợ Đồn',
				'huyen-cho-moi' => 'Huyện Chợ Mới',
				'huyen-na-ri' => 'Huyện Na Rì',
				'huyen-ngan-son' => 'Huyện Ngân Sơn',
				'huyen-pac-nam' => 'Huyện Pác Nặm',
			),
			'BAC-LIEU' => array(
				'thanh-pho-bac-lieu' => 'Thành phố Bạc Liêu',
				'huyen-dong-hai' => 'Huyện Đông Hải',
				'thi-xa-gia-rai' => 'Thị xã Giá Rai',
				'huyen-hoa-binh' => 'Huyện Hoà Bình',
				'huyen-hong-dan' => 'Huyện Hồng Dân',
				'huyen-phuoc-long' => 'Huyện Phước Long',
				'huyen-vinh-loi' => 'Huyện Vĩnh Lợi',
			),
			'BAC-NINH' => array(
				'thanh-pho-bac-ninh' => 'Thành phố Bắc Ninh',
				'huyen-gia-binh' => 'Huyện Gia Bình',
				'huyen-luong-tai' => 'Huyện Lương Tài',
				'huyen-que-vo' => 'Huyện Quế Võ',
				'huyen-thuan-thanh' => 'Huyện Thuận Thành',
				'huyen-tien-du' => 'Huyện Tiên Du',
				'thi-xa-tu-son' => 'Thị xã Từ Sơn',
				'huyen-yen-phong' => 'Huyện Yên Phong',
			),
			'BEN-TRE' => array(
				'huyen-ba-tri' => 'Huyện Ba Tri',
				'thanh-pho-ben-tre' => 'Thành phố Bến Tre',
				'huyen-binh-dai' => 'Huyện Bình Đại',
				'huyen-chau-thanh' => 'Huyện Châu Thành',
				'huyen-cho-lach' => 'Huyện Chợ Lách',
				'huyen-giong-trom' => 'Huyện Giồng Trôm',
				'huyen-mo-cay-bac' => 'Huyện Mỏ Cày Bắc',
				'huyen-mo-cay-nam' => 'Huyện Mỏ Cày Nam',
				'huyen-thanh-phu' => 'Huyện Thạnh Phú',
			),
			'BINH-DINH' => array(
				'huyen-an-lao' => 'Huyện An Lão',
				'thi-xa-an-nhon' => 'Thị xã An Nhơn',
				'huyen-hoai-an' => 'Huyện Hoài Ân',
				'huyen-hoai-nhon' => 'Huyện Hoài Nhơn',
				'huyen-phu-cat' => 'Huyện Phù Cát',
				'huyen-phu-my' => 'Huyện Phù Mỹ',
				'thanh-pho-qui-nhon' => 'Thành phố Qui Nhơn',
				'huyen-tay-son' => 'Huyện Tây Sơn',
				'huyen-tuy-phuoc' => 'Huyện Tuy Phước',
				'huyen-van-canh' => 'Huyện Vân Canh',
				'huyen-vinh-thanh' => 'Huyện Vĩnh Thạnh',
			),
			'BINH-DUONG' => array(
				'huyen-bac-tan-uyen' => 'Huyện Bắc Tân Uyên',
				'huyen-bau-bang' => 'Huyện Bàu Bàng',
				'thi-xa-ben-cat' => 'Thị xã Bến Cát',
				'huyen-dau-tieng' => 'Huyện Dầu Tiếng',
				'thi-xa-di-an' => 'Thị xã Dĩ An',
				'huyen-phu-giao' => 'Huyện Phú Giáo',
				'thi-xa-tan-uyen' => 'Thị xã Tân Uyên',
				'thanh-pho-thu-dau-mot' => 'Thành phố Thủ Dầu Một',
				'thi-xa-thuan-an' => 'Thị xã Thuận An',
			),
			'BINH-PHUOC' => array(
				'thi-xa-binh-long' => 'Thị xã Bình Long',
				'huyen-bu-dang' => 'Huyện Bù Đăng',
				'huyen-bu-dop' => 'Huyện Bù Đốp',
				'huyen-bu-gia-map' => 'Huyện Bù Gia Mập',
				'huyen-chon-thanh' => 'Huyện Chơn Thành',
				'huyen-dong-phu' => 'Huyện Đồng Phú',
				'thanh-pho-dong-xoai' => 'Thành phố Đồng Xoài',
				'huyen-hon-quan' => 'Huyện Hớn Quản',
				'huyen-loc-ninh' => 'Huyện Lộc Ninh',
				'huyen-phu-rieng' => 'Huyện Phú Riềng',
				'thi-xa-phuoc-long' => 'Thị xã Phước Long',
			),
			'BINH-THUAN' => array(
				'huyen-bac-binh' => 'Huyện Bắc Bình',
				'huyen-duc-linh' => 'Huyện Đức Linh',
				'huyen-ham-tan' => 'Huyện Hàm Tân',
				'huyen-ham-thuan-bac' => 'Huyện Hàm Thuận Bắc',
				'huyen-ham-thuan-nam' => 'Huyện Hàm Thuận Nam',
				'thi-xa-la-gi' => 'Thị xã La Gi',
				'thanh-pho-phan-thiet' => 'Thành phố Phan Thiết',
				'huyen-phu-qui' => 'Huyện Phú Quí',
				'huyen-tanh-linh' => 'Huyện Tánh Linh',
				'huyen-tuy-phong' => 'Huyện Tuy Phong',
			),
			'CA-MAU' => array(
				'thanh-pho-ca-mau' => 'Thành phố Cà Mau',
				'huyen-cai-nuoc' => 'Huyện Cái Nước',
				'huyen-dam-doi' => 'Huyện Đầm Dơi',
				'huyen-nam-can' => 'Huyện Năm Căn',
				'huyen-ngoc-hien' => 'Huyện Ngọc Hiển',
				'huyen-phu-tan' => 'Huyện Phú Tân',
				'huyen-thoi-binh' => 'Huyện Thới Bình',
				'huyen-tran-van-thoi' => 'Huyện Trần Văn Thời',
				'huyen-u-minh' => 'Huyện U Minh',
			),
			'CAN-THO' => array(
				'quan-binh-thuy' => 'Quận Bình Thuỷ',
				'quan-cai-rang' => 'Quận Cái Răng',
				'huyen-co-do' => 'Huyện Cờ Đỏ',
				'quan-ninh-kieu' => 'Quận Ninh Kiều',
				'quan-o-mon' => 'Quận Ô Môn',
				'huyen-phong-dien' => 'Huyện Phong Điền',
				'huyen-thoi-lai' => 'Huyện Thới Lai',
				'quan-thot-not' => 'Quận Thốt Nốt',
				'huyen-vinh-thanh' => 'Huyện Vĩnh Thạnh',
			),
			'CAO-BANG' => array(
				'huyen-bao-lac' => 'Huyện Bảo Lạc',
				'huyen-bao-lam' => 'Huyện Bảo Lâm',
				'thanh-pho-cao-bang' => 'Thành phố Cao Bằng',
				'huyen-ha-lang' => 'Huyện Hạ Lang',
				'huyen-ha-quang' => 'Huyện Hà Quảng',
				'huyen-hoa-an' => 'Huyện Hoà An',
				'huyen-nguyen-binh' => 'Huyện Nguyên Bình',
				'huyen-phuc-hoa' => 'Huyện Phục Hoà',
				'huyen-quang-uyen' => 'Huyện Quảng Uyên',
				'huyen-thach-an' => 'Huyện Thạch An',
				'huyen-thong-nong' => 'Huyện Thông Nông',
				'huyen-tra-linh' => 'Huyện Trà Lĩnh',
				'huyen-trung-khanh' => 'Huyện Trùng Khánh',
			),
			'DA-NANG' => array(
				'quan-cam-le' => 'Quận Cẩm Lệ',
				'quan-hai-chau' => 'Quận Hải Châu',
				'huyen-hoa-vang' => 'Huyện Hòa Vang',
				'huyen-hoang-sa' => 'Huyện Hoàng Sa',
				'quan-lien-chieu' => 'Quận Liên Chiểu',
				'quan-ngu-hanh-son' => 'Quận Ngũ Hành Sơn',
				'quan-son-tra' => 'Quận Sơn Trà',
				'quan-thanh-khe' => 'Quận Thanh Khê',
			),
			'DAK-LAK' => array(
				'huyen-buon-don' => 'Huyện Buôn Đôn',
				'thi-xa-buon-ho' => 'Thị Xã Buôn Hồ',
				'thanh-pho-buon-ma-thuot' => 'Thành phố Buôn Ma Thuột',
				'huyen-cu-kuin' => 'Huyện Cư Kuin',
				'huyen-cu-mgar' => 'Huyện Cư M\'gar',
				'huyen-ea-hleo' => 'Huyện Ea H\'leo',
				'huyen-ea-kar' => 'Huyện Ea Kar',
				'huyen-ea-sup' => 'Huyện Ea Súp',
				'huyen-krong-a-na' => 'Huyện Krông A Na',
				'huyen-krong-bong' => 'Huyện Krông Bông',
				'huyen-krong-buk' => 'Huyện Krông Búk',
				'huyen-krong-nang' => 'Huyện Krông Năng',
				'huyen-krong-pac' => 'Huyện Krông Pắc',
				'huyen-lak' => 'Huyện Lắk',
				'huyen-mdrak' => 'Huyện M\'Đrắk',
			),
			'DAK-NONG' => array(
				'huyen-cu-jut' => 'Huyện Cư Jút',
				'huyen-dak-glong' => 'Huyện Đăk Glong',
				'huyen-dak-mil' => 'Huyện Đắk Mil',
				'huyen-dak-rlap' => 'Huyện Đắk R\'Lấp',
				'huyen-dak-song' => 'Huyện Đắk Song',
				'thi-xa-gia-nghia' => 'Thị xã Gia Nghĩa',
				'huyen-krong-no' => 'Huyện Krông Nô',
				'huyen-tuy-duc' => 'Huyện Tuy Đức',
			),
			'DIEN-BIEN' => array(
				'huyen-dien-bien' => 'Huyện Điện Biên',
				'huyen-dien-bien-dong' => 'Huyện Điện Biên Đông',
				'thanh-pho-dien-bien-phu' => 'Thành phố Điện Biên Phủ',
				'huyen-muong-ang' => 'Huyện Mường Ảng',
				'huyen-muong-cha' => 'Huyện Mường Chà',
				'thi-xa-muong-lay' => 'Thị Xã Mường Lay',
				'huyen-muong-nhe' => 'Huyện Mường Nhé',
				'huyen-nam-po' => 'Huyện Nậm Pồ',
				'huyen-tua-chua' => 'Huyện Tủa Chùa',
				'huyen-tuan-giao' => 'Huyện Tuần Giáo',
			),
			'DONG-NAI' => array(
				'thanh-pho-bien-hoa' => 'Thành phố Biên Hòa',
				'huyen-cam-my' => 'Huyện Cẩm Mỹ',
				'huyen-dinh-quan' => 'Huyện Định Quán',
				'thanh-pho-long-khanh' => 'Thành phố Long Khánh',
				'huyen-long-thanh' => 'Huyện Long Thành',
				'huyen-nhon-trach' => 'Huyện Nhơn Trạch',
				'huyen-tan-phu' => 'Huyện Tân Phú',
				'huyen-thong-nhat' => 'Huyện Thống Nhất',
				'huyen-trang-bom' => 'Huyện Trảng Bom',
				'huyen-vinh-cuu' => 'Huyện Vĩnh Cửu',
				'huyen-xuan-loc' => 'Huyện Xuân Lộc',
			),
			'DONG-THAP' => array(
				'thanh-pho-cao-lanh' => 'Thành phố Cao Lãnh',
				'huyen-cao-lanh' => 'Huyện Cao Lãnh',
				'huyen-chau-thanh' => 'Huyện Châu Thành',
				'thi-xa-hong-ngu' => 'Thị xã Hồng Ngự',
				'huyen-hong-ngu' => 'Huyện Hồng Ngự',
				'huyen-lai-vung' => 'Huyện Lai Vung',
				'huyen-lap-vo' => 'Huyện Lấp Vò',
				'thanh-pho-sa-dec' => 'Thành phố Sa Đéc',
				'huyen-tam-nong' => 'Huyện Tam Nông',
				'huyen-tan-hong' => 'Huyện Tân Hồng',
				'huyen-thanh-binh' => 'Huyện Thanh Bình',
				'huyen-thap-muoi' => 'Huyện Tháp Mười',
			),
			'GIA-LAI' => array(
				'thi-xa-an-khe' => 'Thị xã An Khê',
				'thi-xa-ayun-pa' => 'Thị xã Ayun Pa',
				'huyen-chu-pah' => 'Huyện Chư Păh',
				'huyen-chu-prong' => 'Huyện Chư Prông',
				'huyen-chu-puh' => 'Huyện Chư Pưh',
				'huyen-chu-se' => 'Huyện Chư Sê',
				'huyen-dak-doa' => 'Huyện Đăk Đoa',
				'huyen-dak-po' => 'Huyện Đăk Pơ',
				'huyen-duc-co' => 'Huyện Đức Cơ',
				'huyen-ia-grai' => 'Huyện Ia Grai',
				'huyen-ia-pa' => 'Huyện Ia Pa',
				'huyen-kbang' => 'Huyện KBang',
				'huyen-kong-chro' => 'Huyện Kông Chro',
				'huyen-krong-pa' => 'Huyện Krông Pa',
				'huyen-mang-yang' => 'Huyện Mang Yang',
				'huyen-phu-thien' => 'Huyện Phú Thiện',
				'thanh-pho-pleiku' => 'Thành phố Pleiku',
			),
			'HA-GIANG' => array(
				'huyen-bac-me' => 'Huyện Bắc Mê',
				'huyen-bac-quang' => 'Huyện Bắc Quang',
				'huyen-dong-van' => 'Huyện Đồng Văn',
				'thanh-pho-ha-giang' => 'Thành phố Hà Giang',
				'huyen-hoang-su-phi' => 'Huyện Hoàng Su Phì',
				'huyen-meo-vac' => 'Huyện Mèo Vạc',
				'huyen-quan-ba' => 'Huyện Quản Bạ',
				'huyen-quang-binh' => 'Huyện Quang Bình',
				'huyen-vi-xuyen' => 'Huyện Vị Xuyên',
				'huyen-xin-man' => 'Huyện Xín Mần',
				'huyen-yen-minh' => 'Huyện Yên Minh',
			),
			'HA-NAM' => array(
				'huyen-binh-luc' => 'Huyện Bình Lục',
				'huyen-duy-tien' => 'Huyện Duy Tiên',
				'huyen-kim-bang' => 'Huyện Kim Bảng',
				'huyen-ly-nhan' => 'Huyện Lý Nhân',
				'thanh-pho-phu-ly' => 'Thành phố Phủ Lý',
				'huyen-thanh-liem' => 'Huyện Thanh Liêm',
			),
			'HA-NOI' => array(
				'quan-ba-dinh' => 'Quận Ba Đình',
				'huyen-ba-vi' => 'Huyện Ba Vì',
				'quan-bac-tu-liem' => 'Quận Bắc Từ Liêm',
				'quan-cau-giay' => 'Quận Cầu Giấy',
				'huyen-chuong-my' => 'Huyện Chương Mỹ',
				'huyen-dan-phuong' => 'Huyện Đan Phượng',
				'huyen-dong-anh' => 'Huyện Đông Anh',
				'quan-dong-da' => 'Quận Đống Đa',
				'huyen-gia-lam' => 'Huyện Gia Lâm',
				'quan-ha-dong' => 'Quận Hà Đông',
				'quan-hai-ba-trung' => 'Quận Hai Bà Trưng',
				'huyen-hoai-duc' => 'Huyện Hoài Đức',
				'quan-hoan-kiem' => 'Quận Hoàn Kiếm',
				'quan-hoang-mai' => 'Quận Hoàng Mai',
				'quan-long-bien' => 'Quận Long Biên',
				'huyen-me-linh' => 'Huyện Mê Linh',
				'huyen-my-duc' => 'Huyện Mỹ Đức',
				'quan-nam-tu-liem' => 'Quận Nam Từ Liêm',
				'huyen-phu-xuyen' => 'Huyện Phú Xuyên',
				'huyen-phuc-tho' => 'Huyện Phúc Thọ',
				'huyen-quoc-oai' => 'Huyện Quốc Oai',
				'huyen-soc-son' => 'Huyện Sóc Sơn',
				'thi-xa-son-tay' => 'Thị xã Sơn Tây',
				'quan-tay-ho' => 'Quận Tây Hồ',
				'huyen-thach-that' => 'Huyện Thạch Thất',
				'huyen-thanh-oai' => 'Huyện Thanh Oai',
				'huyen-thanh-tri' => 'Huyện Thanh Trì',
				'quan-thanh-xuan' => 'Quận Thanh Xuân',
				'huyen-thuong-tin' => 'Huyện Thường Tín',
				'huyen-ung-hoa' => 'Huyện Ứng Hòa',
			),
			'HA-TINH' => array(
				'huyen-cam-xuyen' => 'Huyện Cẩm Xuyên',
				'huyen-can-loc' => 'Huyện Can Lộc',
				'huyen-duc-tho' => 'Huyện Đức Thọ',
				'thanh-pho-ha-tinh' => 'Thành phố Hà Tĩnh',
				'thi-xa-hong-linh' => 'Thị xã Hồng Lĩnh',
				'huyen-huong-khe' => 'Huyện Hương Khê',
				'huyen-huong-son' => 'Huyện Hương Sơn',
				'huyen-ky-anh' => 'Huyện Kỳ Anh',
				'thi-xa-ky-anh' => 'Thị xã Kỳ Anh',
				'huyen-loc-ha' => 'Huyện Lộc Hà',
				'huyen-nghi-xuan' => 'Huyện Nghi Xuân',
				'huyen-thach-ha' => 'Huyện Thạch Hà',
				'huyen-vu-quang' => 'Huyện Vũ Quang',
			),
			'HAI-DUONG' => array(
				'huyen-binh-giang' => 'Huyện Bình Giang',
				'huyen-cam-giang' => 'Huyện Cẩm Giàng',
				'thanh-pho-chi-linh' => 'Thành phố Chí Linh',
				'huyen-gia-loc' => 'Huyện Gia Lộc',
				'thanh-pho-hai-duong' => 'Thành phố Hải Dương',
				'huyen-kim-thanh' => 'Huyện Kim Thành',
				'thi-xa-kinh-mon' => 'Thị xã Kinh Môn',
				'huyen-nam-sach' => 'Huyện Nam Sách',
				'huyen-ninh-giang' => 'Huyện Ninh Giang',
				'huyen-thanh-ha' => 'Huyện Thanh Hà',
				'huyen-thanh-mien' => 'Huyện Thanh Miện',
				'huyen-tu-ky' => 'Huyện Tứ Kỳ',
			),
			'HAI-PHONG' => array(
				'huyen-an-duong' => 'Huyện An Dương',
				'huyen-an-lao' => 'Huyện An Lão',
				'huyen-bach-long-vi' => 'Huyện Bạch Long Vĩ',
				'huyen-cat-hai' => 'Huyện Cát Hải',
				'quan-do-son' => 'Quận Đồ Sơn',
				'quan-duong-kinh' => 'Quận Dương Kinh',
				'quan-hai-an' => 'Quận Hải An',
				'quan-hong-bang' => 'Quận Hồng Bàng',
				'quan-kien-an' => 'Quận Kiến An',
				'huyen-kien-thuy' => 'Huyện Kiến Thuỵ',
				'quan-le-chan' => 'Quận Lê Chân',
				'quan-ngo-quyen' => 'Quận Ngô Quyền',
				'huyen-thuy-nguyen' => 'Huyện Thuỷ Nguyên',
				'huyen-tien-lang' => 'Huyện Tiên Lãng',
				'huyen-vinh-bao' => 'Huyện Vĩnh Bảo',
			),
			'HAU-GIANG' => array(
				'huyen-chau-thanh' => 'Huyện Châu Thành',
				'huyen-chau-thanh-a' => 'Huyện Châu Thành A',
				'huyen-long-my' => 'Huyện Long Mỹ',
				'thi-xa-long-my' => 'Thị xã Long Mỹ',
				'thi-xa-nga-bay' => 'Thị xã Ngã Bảy',
				'huyen-phung-hiep' => 'Huyện Phụng Hiệp',
				'thanh-pho-vi-thanh' => 'Thành phố Vị Thanh',
				'huyen-vi-thuy' => 'Huyện Vị Thuỷ',
			),
			'HO-CHI-MINH' => array(
				'quan-1' => 'Quận 1',
				'quan-2' => 'Quận 2',
				'quan-3' => 'Quận 3',
				'quan-4' => 'Quận 4',
				'quan-5' => 'Quận 5',
				'quan-6' => 'Quận 6',
				'quan-7' => 'Quận 7',
				'quan-8' => 'Quận 8',
				'quan-9' => 'Quận 9',
				'quan-10' => 'Quận 10',
				'quan-11' => 'Quận 11',
				'quan-12' => 'Quận 12',
				'huyen-binh-chanh' => 'Huyện Bình Chánh',
				'quan-binh-tan' => 'Quận Bình Tân',
				'quan-binh-thanh' => 'Quận Bình Thạnh',
				'huyen-can-gio' => 'Huyện Cần Giờ',
				'huyen-cu-chi' => 'Huyện Củ Chi',
				'quan-go-vap' => 'Quận Gò Vấp',
				'huyen-hoc-mon' => 'Huyện Hóc Môn',
				'huyen-nha-be' => 'Huyện Nhà Bè',
				'quan-phu-nhuan' => 'Quận Phú Nhuận',
				'quan-tan-binh' => 'Quận Tân Bình',
				'quan-tan-phu' => 'Quận Tân Phú',
				'quan-thu-duc' => 'Quận Thủ Đức',
			),
			'HOA-BINH' => array(
				'huyen-cao-phong' => 'Huyện Cao Phong',
				'huyen-da-bac' => 'Huyện Đà Bắc',
				'thanh-pho-hoa-binh' => 'Thành phố Hòa Bình',
				'huyen-kim-boi' => 'Huyện Kim Bôi',
				'huyen-ky-son' => 'Huyện Kỳ Sơn',
				'huyen-lac-son' => 'Huyện Lạc Sơn',
				'huyen-lac-thuy' => 'Huyện Lạc Thủy',
				'huyen-luong-son' => 'Huyện Lương Sơn',
				'huyen-mai-chau' => 'Huyện Mai Châu',
				'huyen-tan-lac' => 'Huyện Tân Lạc',
				'huyen-yen-thuy' => 'Huyện Yên Thủy',
			),
			'HUNG-YEN' => array(
				'huyen-an-thi' => 'Huyện Ân Thi',
				'thanh-pho-hung-yen' => 'Thành phố Hưng Yên',
				'huyen-khoai-chau' => 'Huyện Khoái Châu',
				'huyen-kim-dong' => 'Huyện Kim Động',
				'thi-xa-my-hao' => 'Thị xã Mỹ Hào',
				'huyen-phu-cu' => 'Huyện Phù Cừ',
				'huyen-tien-lu' => 'Huyện Tiên Lữ',
				'huyen-van-giang' => 'Huyện Văn Giang',
				'huyen-van-lam' => 'Huyện Văn Lâm',
				'huyen-yen-my' => 'Huyện Yên Mỹ',
			),
			'KHANH-HOA' => array(
				'huyen-cam-lam' => 'Huyện Cam Lâm',
				'thanh-pho-cam-ranh' => 'Thành phố Cam Ranh',
				'huyen-dien-khanh' => 'Huyện Diên Khánh',
				'huyen-khanh-son' => 'Huyện Khánh Sơn',
				'huyen-khanh-vinh' => 'Huyện Khánh Vĩnh',
				'thanh-pho-nha-trang' => 'Thành phố Nha Trang',
				'thi-xa-ninh-hoa' => 'Thị xã Ninh Hòa',
				'huyen-truong-sa' => 'Huyện Trường Sa',
				'huyen-van-ninh' => 'Huyện Vạn Ninh',
			),
			'KIEN-GIANG' => array(
				'huyen-an-bien' => 'Huyện An Biên',
				'huyen-an-minh' => 'Huyện An Minh',
				'huyen-chau-thanh' => 'Huyện Châu Thành',
				'huyen-giang-thanh' => 'Huyện Giang Thành',
				'huyen-giong-rieng' => 'Huyện Giồng Riềng',
				'huyen-go-quao' => 'Huyện Gò Quao',
				'thanh-pho-ha-tien' => 'Thành phố Hà Tiên',
				'huyen-hon-dat' => 'Huyện Hòn Đất',
				'huyen-kien-hai' => 'Huyện Kiên Hải',
				'huyen-kien-luong' => 'Huyện Kiên Lương',
				'huyen-phu-quoc' => 'Huyện Phú Quốc',
				'thanh-pho-rach-gia' => 'Thành phố Rạch Giá',
				'huyen-tan-hiep' => 'Huyện Tân Hiệp',
				'huyen-u-minh-thuong' => 'Huyện U Minh Thượng',
				'huyen-vinh-thuan' => 'Huyện Vĩnh Thuận',
			),
			'KON-TUM' => array(
				'huyen-dak-glei' => 'Huyện Đắk Glei',
				'huyen-dak-ha' => 'Huyện Đắk Hà',
				'huyen-dak-to' => 'Huyện Đắk Tô',
				'huyen-ia-h-drai' => 'Huyện Ia H\' Drai',
				'huyen-kon-plong' => 'Huyện Kon Plông',
				'huyen-kon-ray' => 'Huyện Kon Rẫy',
				'thanh-pho-kon-tum' => 'Thành phố Kon Tum',
				'huyen-ngoc-hoi' => 'Huyện Ngọc Hồi',
				'huyen-sa-thay' => 'Huyện Sa Thầy',
				'huyen-tu-mo-rong' => 'Huyện Tu Mơ Rông',
			),
			'LAI-CHAU' => array(
				'thanh-pho-lai-chau' => 'Thành phố Lai Châu',
				'huyen-muong-te' => 'Huyện Mường Tè',
				'huyen-nam-nhun' => 'Huyện Nậm Nhùn',
				'huyen-phong-tho' => 'Huyện Phong Thổ',
				'huyen-sin-ho' => 'Huyện Sìn Hồ',
				'huyen-tam-duong' => 'Huyện Tam Đường',
				'huyen-tan-uyen' => 'Huyện Tân Uyên',
				'huyen-than-uyen' => 'Huyện Than Uyên',
			),
			'LAM-DONG' => array(
				'huyen-bao-lam' => 'Huyện Bảo Lâm',
				'thanh-pho-bao-loc' => 'Thành phố Bảo Lộc',
				'huyen-cat-tien' => 'Huyện Cát Tiên',
				'huyen-da-huoai' => 'Huyện Đạ Huoai',
				'thanh-pho-da-lat' => 'Thành phố Đà Lạt',
				'huyen-da-teh' => 'Huyện Đạ Tẻh',
				'huyen-dam-rong' => 'Huyện Đam Rông',
				'huyen-di-linh' => 'Huyện Di Linh',
				'huyen-don-duong' => 'Huyện Đơn Dương',
				'huyen-duc-trong' => 'Huyện Đức Trọng',
				'huyen-lac-duong' => 'Huyện Lạc Dương',
				'huyen-lam-ha' => 'Huyện Lâm Hà',
			),
			'LANG-SON' => array(
				'huyen-bac-son' => 'Huyện Bắc Sơn',
				'huyen-binh-gia' => 'Huyện Bình Gia',
				'huyen-cao-loc' => 'Huyện Cao Lộc',
				'huyen-chi-lang' => 'Huyện Chi Lăng',
				'huyen-dinh-lap' => 'Huyện Đình Lập',
				'huyen-huu-lung' => 'Huyện Hữu Lũng',
				'thanh-pho-lang-son' => 'Thành phố Lạng Sơn',
				'huyen-loc-binh' => 'Huyện Lộc Bình',
				'huyen-trang-dinh' => 'Huyện Tràng Định',
				'huyen-van-lang' => 'Huyện Văn Lãng',
				'huyen-van-quan' => 'Huyện Văn Quan',
			),
			'LAO-CAI' => array(
				'huyen-bac-ha' => 'Huyện Bắc Hà',
				'huyen-bao-thang' => 'Huyện Bảo Thắng',
				'huyen-bao-yen' => 'Huyện Bảo Yên',
				'huyen-bat-xat' => 'Huyện Bát Xát',
				'thanh-pho-lao-cai' => 'Thành phố Lào Cai',
				'huyen-muong-khuong' => 'Huyện Mường Khương',
				'thi-xa-sa-pa' => 'Thị xã Sa Pa',
				'huyen-si-ma-cai' => 'Huyện Si Ma Cai',
				'huyen-van-ban' => 'Huyện Văn Bàn',
			),
			'LONG-AN' => array(
				'huyen-ben-luc' => 'Huyện Bến Lức',
				'huyen-can-duoc' => 'Huyện Cần Đước',
				'huyen-can-giuoc' => 'Huyện Cần Giuộc',
				'huyen-chau-thanh' => 'Huyện Châu Thành',
				'huyen-duc-hoa' => 'Huyện Đức Hòa',
				'huyen-duc-hue' => 'Huyện Đức Huệ',
				'thi-xa-kien-tuong' => 'Thị xã Kiến Tường',
				'huyen-moc-hoa' => 'Huyện Mộc Hóa',
				'thanh-pho-tan-an' => 'Thành phố Tân An',
				'huyen-tan-hung' => 'Huyện Tân Hưng',
				'huyen-tan-thanh' => 'Huyện Tân Thạnh',
				'huyen-tan-tru' => 'Huyện Tân Trụ',
				'huyen-thanh-hoa' => 'Huyện Thạnh Hóa',
				'huyen-thu-thua' => 'Huyện Thủ Thừa',
				'huyen-vinh-hung' => 'Huyện Vĩnh Hưng',
			),
			'NAM-DINH' => array(
				'huyen-giao-thuy' => 'Huyện Giao Thủy',
				'huyen-hai-hau' => 'Huyện Hải Hậu',
				'huyen-my-loc' => 'Huyện Mỹ Lộc',
				'thanh-pho-nam-dinh' => 'Thành phố Nam Định',
				'huyen-nam-truc' => 'Huyện Nam Trực',
				'huyen-nghia-hung' => 'Huyện Nghĩa Hưng',
				'huyen-truc-ninh' => 'Huyện Trực Ninh',
				'huyen-vu-ban' => 'Huyện Vụ Bản',
				'huyen-xuan-truong' => 'Huyện Xuân Trường',
				'huyen-y-yen' => 'Huyện Ý Yên',
			),
			'NGHE-AN' => array(
				'huyen-anh-son' => 'Huyện Anh Sơn',
				'huyen-con-cuong' => 'Huyện Con Cuông',
				'thi-xa-cua-lo' => 'Thị xã Cửa Lò',
				'huyen-dien-chau' => 'Huyện Diễn Châu',
				'huyen-do-luong' => 'Huyện Đô Lương',
				'thi-xa-hoang-mai' => 'Thị xã Hoàng Mai',
				'huyen-hung-nguyen' => 'Huyện Hưng Nguyên',
				'huyen-ky-son' => 'Huyện Kỳ Sơn',
				'huyen-nam-dan' => 'Huyện Nam Đàn',
				'huyen-nghi-loc' => 'Huyện Nghi Lộc',
				'huyen-nghia-dan' => 'Huyện Nghĩa Đàn',
				'huyen-que-phong' => 'Huyện Quế Phong',
				'huyen-quy-chau' => 'Huyện Quỳ Châu',
				'huyen-quy-hop' => 'Huyện Quỳ Hợp',
				'huyen-quynh-luu' => 'Huyện Quỳnh Lưu',
				'huyen-tan-ky' => 'Huyện Tân Kỳ',
				'thi-xa-thai-hoa' => 'Thị xã Thái Hoà',
				'huyen-thanh-chuong' => 'Huyện Thanh Chương',
				'huyen-tuong-duong' => 'Huyện Tương Dương',
				'thanh-pho-vinh' => 'Thành phố Vinh',
				'huyen-yen-thanh' => 'Huyện Yên Thành',
			),
			'NINH-BINH' => array(
				'huyen-gia-vien' => 'Huyện Gia Viễn',
				'huyen-hoa-lu' => 'Huyện Hoa Lư',
				'huyen-kim-son' => 'Huyện Kim Sơn',
				'huyen-nho-quan' => 'Huyện Nho Quan',
				'thanh-pho-ninh-binh' => 'Thành phố Ninh Bình',
				'thanh-pho-tam-diep' => 'Thành phố Tam Điệp',
				'huyen-yen-khanh' => 'Huyện Yên Khánh',
				'huyen-yen-mo' => 'Huyện Yên Mô',
			),
			'NINH-THUAN' => array(
				'huyen-bac-ai' => 'Huyện Bác Ái',
				'huyen-ninh-hai' => 'Huyện Ninh Hải',
				'huyen-ninh-phuoc' => 'Huyện Ninh Phước',
				'huyen-ninh-son' => 'Huyện Ninh Sơn',
				'thanh-pho-phan-rang-thap-cham' => 'Thành phố Phan Rang-Tháp Chàm',
				'huyen-thuan-bac' => 'Huyện Thuận Bắc',
				'huyen-thuan-nam' => 'Huyện Thuận Nam',
			),
			'PHU-THO' => array(
				'huyen-cam-khe' => 'Huyện Cẩm Khê',
				'huyen-doan-hung' => 'Huyện Đoan Hùng',
				'huyen-ha-hoa' => 'Huyện Hạ Hoà',
				'huyen-lam-thao' => 'Huyện Lâm Thao',
				'huyen-phu-ninh' => 'Huyện Phù Ninh',
				'thi-xa-phu-tho' => 'Thị xã Phú Thọ',
				'huyen-tam-nong' => 'Huyện Tam Nông',
				'huyen-tan-son' => 'Huyện Tân Sơn',
				'huyen-thanh-ba' => 'Huyện Thanh Ba',
				'huyen-thanh-son' => 'Huyện Thanh Sơn',
				'huyen-thanh-thuy' => 'Huyện Thanh Thuỷ',
				'thanh-pho-viet-tri' => 'Thành phố Việt Trì',
				'huyen-yen-lap' => 'Huyện Yên Lập',
			),
			'PHU-YEN' => array(
				'huyen-dong-hoa' => 'Huyện Đông Hòa',
				'huyen-dong-xuan' => 'Huyện Đồng Xuân',
				'huyen-phu-hoa' => 'Huyện Phú Hoà',
				'huyen-son-hoa' => 'Huyện Sơn Hòa',
				'thi-xa-song-cau' => 'Thị xã Sông Cầu',
				'huyen-song-hinh' => 'Huyện Sông Hinh',
				'huyen-tay-hoa' => 'Huyện Tây Hoà',
				'huyen-tuy-an' => 'Huyện Tuy An',
				'thanh-pho-tuy-hoa' => 'Thành phố Tuy Hoà',
			),
			'QUANG-BINH' => array(
				'thi-xa-ba-don' => 'Thị xã Ba Đồn',
				'huyen-bo-trach' => 'Huyện Bố Trạch',
				'thanh-pho-dong-hoi' => 'Thành Phố Đồng Hới',
				'huyen-le-thuy' => 'Huyện Lệ Thủy',
				'huyen-minh-hoa' => 'Huyện Minh Hóa',
				'huyen-quang-ninh' => 'Huyện Quảng Ninh',
				'huyen-quang-trach' => 'Huyện Quảng Trạch',
				'huyen-tuyen-hoa' => 'Huyện Tuyên Hóa',
			),
			'QUANG-NAM' => array(
				'huyen-bac-tra-my' => 'Huyện Bắc Trà My',
				'huyen-dai-loc' => 'Huyện Đại Lộc',
				'thi-xa-dien-ban' => 'Thị xã Điện Bàn',
				'huyen-dong-giang' => 'Huyện Đông Giang',
				'huyen-duy-xuyen' => 'Huyện Duy Xuyên',
				'huyen-hiep-duc' => 'Huyện Hiệp Đức',
				'thanh-pho-hoi-an' => 'Thành phố Hội An',
				'huyen-nam-giang' => 'Huyện Nam Giang',
				'huyen-nam-tra-my' => 'Huyện Nam Trà My',
				'huyen-nong-son' => 'Huyện Nông Sơn',
				'huyen-nui-thanh' => 'Huyện Núi Thành',
				'huyen-phu-ninh' => 'Huyện Phú Ninh',
				'huyen-phuoc-son' => 'Huyện Phước Sơn',
				'huyen-que-son' => 'Huyện Quế Sơn',
				'thanh-pho-tam-ky' => 'Thành phố Tam Kỳ',
				'huyen-tay-giang' => 'Huyện Tây Giang',
				'huyen-thang-binh' => 'Huyện Thăng Bình',
				'huyen-tien-phuoc' => 'Huyện Tiên Phước',
			),
			'QUANG-NGAI' => array(
				'huyen-ba-to' => 'Huyện Ba Tơ',
				'huyen-binh-son' => 'Huyện Bình Sơn',
				'huyen-duc-pho' => 'Huyện Đức Phổ',
				'huyen-ly-son' => 'Huyện Lý Sơn',
				'huyen-minh-long' => 'Huyện Minh Long',
				'huyen-mo-duc' => 'Huyện Mộ Đức',
				'huyen-nghia-hanh' => 'Huyện Nghĩa Hành',
				'thanh-pho-quang-ngai' => 'Thành phố Quảng Ngãi',
				'huyen-son-ha' => 'Huyện Sơn Hà',
				'huyen-son-tay' => 'Huyện Sơn Tây',
				'huyen-son-tinh' => 'Huyện Sơn Tịnh',
				'huyen-tay-tra' => 'Huyện Tây Trà',
				'huyen-tra-bong' => 'Huyện Trà Bồng',
				'huyen-tu-nghia' => 'Huyện Tư Nghĩa',
			),
			'QUANG-NINH' => array(
				'huyen-ba-che' => 'Huyện Ba Chẽ',
				'huyen-binh-lieu' => 'Huyện Bình Liêu',
				'thanh-pho-cam-pha' => 'Thành phố Cẩm Phả',
				'huyen-co-to' => 'Huyện Cô Tô',
				'huyen-dam-ha' => 'Huyện Đầm Hà',
				'thi-xa-dong-trieu' => 'Thị xã Đông Triều',
				'thanh-pho-ha-long' => 'Thành phố Hạ Long',
				'huyen-hai-ha' => 'Huyện Hải Hà',
				'huyen-hoanh-bo' => 'Huyện Hoành Bồ',
				'thanh-pho-mong-cai' => 'Thành phố Móng Cái',
				'thi-xa-quang-yen' => 'Thị xã Quảng Yên',
				'huyen-tien-yen' => 'Huyện Tiên Yên',
				'thanh-pho-uong-bi' => 'Thành phố Uông Bí',
				'huyen-van-don' => 'Huyện Vân Đồn',
			),
			'QUANG-TRI' => array(
				'huyen-cam-lo' => 'Huyện Cam Lộ',
				'huyen-con-co' => 'Huyện Cồn Cỏ',
				'huyen-da-krong' => 'Huyện Đa Krông',
				'thanh-pho-dong-ha' => 'Thành phố Đông Hà',
				'huyen-gio-linh' => 'Huyện Gio Linh',
				'huyen-hai-lang' => 'Huyện Hải Lăng',
				'huyen-huong-hoa' => 'Huyện Hướng Hóa',
				'thi-xa-quang-tri' => 'Thị xã Quảng Trị',
				'huyen-trieu-phong' => 'Huyện Triệu Phong',
				'huyen-vinh-linh' => 'Huyện Vĩnh Linh',
			),
			'SOC-TRANG' => array(
				'huyen-chau-thanh' => 'Huyện Châu Thành',
				'huyen-cu-lao-dung' => 'Huyện Cù Lao Dung',
				'huyen-ke-sach' => 'Huyện Kế Sách',
				'huyen-long-phu' => 'Huyện Long Phú',
				'huyen-my-tu' => 'Huyện Mỹ Tú',
				'huyen-my-xuyen' => 'Huyện Mỹ Xuyên',
				'thi-xa-nga-nam' => 'Thị xã Ngã Năm',
				'thanh-pho-soc-trang' => 'Thành phố Sóc Trăng',
				'huyen-thanh-tri' => 'Huyện Thạnh Trị',
				'huyen-tran-de' => 'Huyện Trần Đề',
				'thi-xa-vinh-chau' => 'Thị xã Vĩnh Châu',
			),
			'SON-LA' => array(
				'huyen-bac-yen' => 'Huyện Bắc Yên',
				'huyen-mai-son' => 'Huyện Mai Sơn',
				'huyen-moc-chau' => 'Huyện Mộc Châu',
				'huyen-muong-la' => 'Huyện Mường La',
				'huyen-phu-yen' => 'Huyện Phù Yên',
				'huyen-quynh-nhai' => 'Huyện Quỳnh Nhai',
				'thanh-pho-son-la' => 'Thành phố Sơn La',
				'huyen-song-ma' => 'Huyện Sông Mã',
				'huyen-sop-cop' => 'Huyện Sốp Cộp',
				'huyen-thuan-chau' => 'Huyện Thuận Châu',
				'huyen-van-ho' => 'Huyện Vân Hồ',
				'huyen-yen-chau' => 'Huyện Yên Châu',
			),
			'TAY-NINH' => array(
				'huyen-ben-cau' => 'Huyện Bến Cầu',
				'huyen-chau-thanh' => 'Huyện Châu Thành',
				'huyen-duong-minh-chau' => 'Huyện Dương Minh Châu',
				'huyen-go-dau' => 'Huyện Gò Dầu',
				'huyen-hoa-thanh' => 'Huyện Hòa Thành',
				'huyen-tan-bien' => 'Huyện Tân Biên',
				'huyen-tan-chau' => 'Huyện Tân Châu',
				'thanh-pho-tay-ninh' => 'Thành phố Tây Ninh',
				'huyen-trang-bang' => 'Huyện Trảng Bàng',
			),
			'THAI-BINH' => array(
				'huyen-dong-hung' => 'Huyện Đông Hưng',
				'huyen-hung-ha' => 'Huyện Hưng Hà',
				'huyen-kien-xuong' => 'Huyện Kiến Xương',
				'huyen-quynh-phu' => 'Huyện Quỳnh Phụ',
				'thanh-pho-thai-binh' => 'Thành phố Thái Bình',
				'huyen-thai-thuy' => 'Huyện Thái Thụy',
				'huyen-tien-hai' => 'Huyện Tiền Hải',
				'huyen-vu-thu' => 'Huyện Vũ Thư',
			),
			'THAI-NGUYEN' => array(
				'huyen-dai-tu' => 'Huyện Đại Từ',
				'huyen-dinh-hoa' => 'Huyện Định Hóa',
				'huyen-dong-hy' => 'Huyện Đồng Hỷ',
				'thi-xa-pho-yen' => 'Thị xã Phổ Yên',
				'huyen-phu-binh' => 'Huyện Phú Bình',
				'huyen-phu-luong' => 'Huyện Phú Lương',
				'thanh-pho-song-cong' => 'Thành phố Sông Công',
				'thanh-pho-thai-nguyen' => 'Thành phố Thái Nguyên',
				'huyen-vo-nhai' => 'Huyện Võ Nhai',
			),
			'THANH-HOA' => array(
				'huyen-ba-thuoc' => 'Huyện Bá Thước',
				'thi-xa-bim-son' => 'Thị xã Bỉm Sơn',
				'huyen-cam-thuy' => 'Huyện Cẩm Thủy',
				'huyen-dong-son' => 'Huyện Đông Sơn',
				'huyen-ha-trung' => 'Huyện Hà Trung',
				'huyen-hau-loc' => 'Huyện Hậu Lộc',
				'huyen-hoang-hoa' => 'Huyện Hoằng Hóa',
				'huyen-lang-chanh' => 'Huyện Lang Chánh',
				'huyen-muong-lat' => 'Huyện Mường Lát',
				'huyen-nga-son' => 'Huyện Nga Sơn',
				'huyen-ngoc-lac' => 'Huyện Ngọc Lặc',
				'huyen-nhu-thanh' => 'Huyện Như Thanh',
				'huyen-nhu-xuan' => 'Huyện Như Xuân',
				'huyen-nong-cong' => 'Huyện Nông Cống',
				'huyen-quan-hoa' => 'Huyện Quan Hóa',
				'huyen-quan-son' => 'Huyện Quan Sơn',
				'huyen-quang-xuong' => 'Huyện Quảng Xương',
				'thanh-pho-sam-son' => 'Thành phố Sầm Sơn',
				'huyen-thach-thanh' => 'Huyện Thạch Thành',
				'thanh-pho-thanh-hoa' => 'Thành phố Thanh Hóa',
				'huyen-thieu-hoa' => 'Huyện Thiệu Hóa',
				'huyen-tho-xuan' => 'Huyện Thọ Xuân',
				'huyen-thuong-xuan' => 'Huyện Thường Xuân',
				'huyen-tinh-gia' => 'Huyện Tĩnh Gia',
				'huyen-trieu-son' => 'Huyện Triệu Sơn',
				'huyen-vinh-loc' => 'Huyện Vĩnh Lộc',
				'huyen-yen-dinh' => 'Huyện Yên Định',
			),
			'THUA-THIEN-HUE' => array(
				'huyen-a-luoi' => 'Huyện A Lưới',
				'thanh-pho-hue' => 'Thành phố Huế',
				'thi-xa-huong-thuy' => 'Thị xã Hương Thủy',
				'thi-xa-huong-tra' => 'Thị xã Hương Trà',
				'huyen-nam-dong' => 'Huyện Nam Đông',
				'huyen-phong-dien' => 'Huyện Phong Điền',
				'huyen-phu-loc' => 'Huyện Phú Lộc',
				'huyen-phu-vang' => 'Huyện Phú Vang',
				'huyen-quang-dien' => 'Huyện Quảng Điền',
			),
			'TIEN-GIANG' => array(
				'huyen-cai-be' => 'Huyện Cái Bè',
				'thi-xa-cai-lay' => 'Thị xã Cai Lậy',
				'huyen-cai-lay' => 'Huyện Cai Lậy',
				'huyen-chau-thanh' => 'Huyện Châu Thành',
				'huyen-cho-gao' => 'Huyện Chợ Gạo',
				'thi-xa-go-cong' => 'Thị xã Gò Công',
				'huyen-go-cong-dong' => 'Huyện Gò Công Đông',
				'huyen-go-cong-tay' => 'Huyện Gò Công Tây',
				'thanh-pho-my-tho' => 'Thành phố Mỹ Tho',
				'huyen-tan-phu-dong' => 'Huyện Tân Phú Đông',
				'huyen-tan-phuoc' => 'Huyện Tân Phước',
			),
			'TRA-VINH' => array(
				'huyen-cang-long' => 'Huyện Càng Long',
				'huyen-cau-ke' => 'Huyện Cầu Kè',
				'huyen-cau-ngang' => 'Huyện Cầu Ngang',
				'huyen-chau-thanh' => 'Huyện Châu Thành',
				'huyen-duyen-hai' => 'Huyện Duyên Hải',
				'thi-xa-duyen-hai' => 'Thị xã Duyên Hải',
				'huyen-tieu-can' => 'Huyện Tiểu Cần',
				'huyen-tra-cu' => 'Huyện Trà Cú',
				'thanh-pho-tra-vinh' => 'Thành phố Trà Vinh',
			),
			'TUYEN-QUANG' => array(
				'huyen-chiem-hoa' => 'Huyện Chiêm Hóa',
				'huyen-ham-yen' => 'Huyện Hàm Yên',
				'huyen-lam-binh' => 'Huyện Lâm Bình',
				'huyen-na-hang' => 'Huyện Na Hang',
				'huyen-son-duong' => 'Huyện Sơn Dương',
				'thanh-pho-tuyen-quang' => 'Thành phố Tuyên Quang',
				'huyen-yen-son' => 'Huyện Yên Sơn',
			),
			'VINH-LONG' => array(
				'huyen-vung-liem' => 'Huyện Vũng Liêm',
				'thi-xa-binh-minh' => 'Thị xã Bình Minh',
				'huyen-binh-tan' => 'Huyện Bình Tân',
				'huyen-long-ho' => 'Huyện Long Hồ',
				'huyen-mang-thit' => 'Huyện Mang Thít',
				'huyen-tam-binh' => 'Huyện Tam Bình',
				'huyen-tra-on' => 'Huyện Trà Ôn',
				'thanh-pho-vinh-long' => 'Thành phố Vĩnh Long',
			),
			'VINH-PHUC' => array(
				'huyen-binh-xuyen' => 'Huyện Bình Xuyên',
				'huyen-lap-thach' => 'Huyện Lập Thạch',
				'thanh-pho-phuc-yen' => 'Thành phố Phúc Yên',
				'huyen-song-lo' => 'Huyện Sông Lô',
				'huyen-tam-dao' => 'Huyện Tam Đảo',
				'huyen-tam-duong' => 'Huyện Tam Dương',
				'huyen-vinh-tuong' => 'Huyện Vĩnh Tường',
				'thanh-pho-vinh-yen' => 'Thành phố Vĩnh Yên',
				'huyen-yen-lac' => 'Huyện Yên Lạc',
			),
			'YEN-BAI' => array(
				'huyen-luc-yen' => 'Huyện Lục Yên',
				'huyen-mu-cang-chai' => 'Huyện Mù Căng Chải',
				'thi-xa-nghia-lo' => 'Thị xã Nghĩa Lộ',
				'huyen-tram-tau' => 'Huyện Trạm Tấu',
				'huyen-tran-yen' => 'Huyện Trấn Yên',
				'huyen-van-chan' => 'Huyện Văn Chấn',
				'huyen-van-yen' => 'Huyện Văn Yên',
				'thanh-pho-yen-bai' => 'Thành phố Yên Bái',
				'huyen-yen-binh' => 'Huyện Yên Bình',
			)
		);
	}

	/**
	 * Enqueue provinces scripts
	 *
	 * Arrange the address field orders to the Vietnam standard in the checkout page: Country - Province - District - Address
	 * @author    Longkt
	 * @since    1.4
	 */
	public function load_provinces_scripts() {
		// Enqueue province style
		wp_enqueue_style( 'woo-viet-provinces-style', WOO_VIET_URL . 'assets/provinces.css' );

		// Enqueue province script
		wp_enqueue_script( 'woo-viet-provinces-script', WOO_VIET_URL . 'assets/provinces.js', array( 'jquery' ), '1.0', true );
	}
}
new WooViet_Provinces();