<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * The class to handle Vietnam Provinces
 *
 * @author   Viet Nguyen
 * @since    1.0
 *
 */
class Provinces {

	/**
	 * Constructor: Add filters
	 */
	public function __construct() {
		add_filter( 'woocommerce_states', array( $this, 'add_provinces' ) );
		add_filter( 'woocommerce_get_country_locale', array( $this, 'edit_vn_locale' ) );
		add_filter( 'woocommerce_localisation_address_formats', array( $this, 'edit_vn_address_formats' ) );
	}

	/**
	 * Change the address format of Vietnam, add {state} (or "Province" in Vietnam)
	 *
	 * @param $array
	 *
	 * @return array
	 */
	public function edit_vn_address_formats( $array ) {

		$array['VN'] = "{name}\n{company}\n{address_1}\n{state}\n{country}";

		return $array;

	}

	/**
	 * Change the way displaying address fields in the checkout page when selecting Vietnam
	 *
	 * @param $array
	 *
	 * @return array
	 */
	public function edit_vn_locale( $array ) {
		$array['VN']['state']['label']    = __( 'Province - District', 'bbs' );
		$array['VN']['state']['required'] = true;
		$array['VN']['city']['hidden'] = true;
		$array['VN']['city']['required'] = false;
		$array['VN']['postcode']['hidden'] = true;
		return $array;
	}


	/**
	 * Add 63 provinces of Vietnam
	 *
	 * @param $states
	 *
	 * @return array
	 */
	public function add_provinces( $states ) {
	
		$states['VN'] = $this->create_VN_state();
		return $states;

	}
	public function create_VN_state(){
		$list_provinces = $this->list_VN_provinces();
		$list_cities = $this->list_VN_cities();
		$vn_states = [];
		foreach ($list_cities as $lkey => $cities){
			foreach ($cities as $key => $city){
				$vn_states["$lkey--$key"] = "{$list_provinces[$lkey]} - $city";
			}
		}
		return $vn_states;
	}
	public function list_VN_provinces(){
		return  array(
			'AN-GIANG'        => __( 'An Giang', 'bbs' ),
			'BA-RIA-VUNG-TAU' => __( 'Ba Ria - Vung Tau', 'bbs' ),
			'BAC-LIEU'        => __( 'Bac Lieu', 'bbs' ),
			'BAC-KAN'         => __( 'Bac Kan', 'bbs' ),
			'BAC-GIANG'       => __( 'Bac Giang', 'bbs' ),
			'BAC-NINH'        => __( 'Bac Ninh', 'bbs' ),
			'BEN-TRE'         => __( 'Ben Tre', 'bbs' ),
			'BINH-DUONG'      => __( 'Binh Duong', 'bbs' ),
			'BINH-DINH'       => __( 'Binh Dinh', 'bbs' ),
			'BINH-PHUOC'      => __( 'Binh Phuoc', 'bbs' ),
			'BINH-THUAN'      => __( 'Binh Thuan', 'bbs' ),
			'CA-MAU'          => __( 'Ca Mau', 'bbs' ),
			'CAO-BANG'        => __( 'Cao Bang', 'bbs' ),
			'CAN-THO'         => __( 'Can Tho', 'bbs' ),
			'DA-NANG'         => __( 'Da Nang', 'bbs' ),
			'DAK-LAK'         => __( 'Dak Lak', 'bbs' ),
			'DAK-NONG'        => __( 'Dak Nong', 'bbs' ),
			'DONG-NAI'        => __( 'Dong Nai', 'bbs' ),
			'DONG-THAP'       => __( 'Dong Thap', 'bbs' ),
			'DIEN-BIEN'       => __( 'Dien Bien', 'bbs' ),
			'GIA-LAI'         => __( 'Gia Lai', 'bbs' ),
			'HA-GIANG'        => __( 'Ha Giang', 'bbs' ),
			'HA-NAM'          => __( 'Ha Nam', 'bbs' ),
			'HA-NOI'          => __( 'Ha Noi', 'bbs' ),
			'HA-TINH'         => __( 'Ha Tinh', 'bbs' ),
			'HAI-DUONG'       => __( 'Hai Duong', 'bbs' ),
			'HAI-PHONG'       => __( 'Hai Phong', 'bbs' ),
			'HOA-BINH'        => __( 'Hoa Binh', 'bbs' ),
			'HAU-GIANG'       => __( 'Hau Giang', 'bbs' ),
			'HUNG-YEN'        => __( 'Hung Yen', 'bbs' ),
			'HO-CHI-MINH'     => __( 'Ho Chi Minh', 'bbs' ),
			'KHANH-HOA'       => __( 'Khanh Hoa', 'bbs' ),
			'KIEN-GIANG'      => __( 'Kien Giang', 'bbs' ),
			'KON-TUM'         => __( 'Kon Tum', 'bbs' ),
			'LAI-CHAU'        => __( 'Lai Chau', 'bbs' ),
			'LAO-CAI'         => __( 'Lao Cai', 'bbs' ),
			'LANG-SON'        => __( 'Lang Son', 'bbs' ),
			'LAM-DONG'        => __( 'Lam Dong', 'bbs' ),
			'LONG-AN'         => __( 'Long An', 'bbs' ),
			'NAM-DINH'        => __( 'Nam Dinh', 'bbs' ),
			'NGHE-AN'         => __( 'Nghe An', 'bbs' ),
			'NINH-BINH'       => __( 'Ninh Binh', 'bbs' ),
			'NINH-THUAN'      => __( 'Ninh Thuan', 'bbs' ),
			'PHU-THO'         => __( 'Phu Tho', 'bbs' ),
			'PHU-YEN'         => __( 'Phu Yen', 'bbs' ),
			'QUANG-BINH'      => __( 'Quang Binh', 'bbs' ),
			'QUANG-NAM'       => __( 'Quang Nam', 'bbs' ),
			'QUANG-NGAI'      => __( 'Quang Ngai', 'bbs' ),
			'QUANG-NINH'      => __( 'Quang Ninh', 'bbs' ),
			'QUANG-TRI'       => __( 'Quang Tri', 'bbs' ),
			'SOC-TRANG'       => __( 'Soc Trang', 'bbs' ),
			'SON-LA'          => __( 'Son La', 'bbs' ),
			'TAY-NINH'        => __( 'Tay Ninh', 'bbs' ),
			'THAI-BINH'       => __( 'Thai Binh', 'bbs' ),
			'THAI-NGUYEN'     => __( 'Thai Nguyen', 'bbs' ),
			'THANH-HOA'       => __( 'Thanh Hoa', 'bbs' ),
			'THUA-THIEN-HUE'  => __( 'Thua Thien - Hue', 'bbs' ),
			'TIEN-GIANG'      => __( 'Tien Giang', 'bbs' ),
			'TRA-VINH'        => __( 'Tra Vinh', 'bbs' ),
			'TUYEN-QUANG'     => __( 'Tuyen Quang', 'bbs' ),
			'VINH-LONG'       => __( 'Vinh Long', 'bbs' ),
			'VINH-PHUC'       => __( 'Vinh Phuc', 'bbs' ),
			'YEN-BAI'         => __( 'Yen Bai', 'bbs' ),
		);
	}
	public function list_VN_cities(){
		return array(
			'AN-GIANG' => array(
				'HUYEN-AN-PHU' => 'Huyện An Phú',
				'THANH-PHO-CHAU-DOC' => 'Thành phố Châu Đốc',
				'HUYEN-CHAU-PHU' => 'Huyện Châu Phú',
				'HUYEN-CHAU-THANH' => 'Huyện Châu Thành',
				'HUYEN-CHO-MOI' => 'Huyện Chợ Mới',
				'THANH-PHO-LONG-XUYEN' => 'Thành phố Long Xuyên',
				'HUYEN-PHU-TAN' => 'Huyện Phú Tân',
				'THI-XA-TAN-CHAU' => 'Thị xã Tân Châu',
				'HUYEN-THOAI-SON' => 'Huyện Thoại Sơn',
				'HUYEN-TINH-BIEN' => 'Huyện Tịnh Biên',
				'HUYEN-TRI-TON' => 'Huyện Tri Tôn',
			),
			'BA-RIA-VUNG-TAU' => array(
				'THANH-PHO-BA-RIA' => 'Thành phố Bà Rịa',
				'HUYEN-CHAU-DUC' => 'Huyện Châu Đức',
				'HUYEN-CON-DAO' => 'Huyện Côn Đảo',
				'HUYEN-DAT-DO' => 'Huyện Đất Đỏ',
				'HUYEN-LONG-DIEN' => 'Huyện Long Điền',
				'THI-XA-PHU-MY' => 'Thị xã Phú Mỹ',
				'THANH-PHO-VUNG-TAU' => 'Thành phố Vũng Tàu',
				'HUYEN-XUYEN-MOC' => 'Huyện Xuyên Mộc',
			),
			'BAC-GIANG' => array(
				'THANH-PHO-BAC-GIANG' => 'Thành phố Bắc Giang',
				'HUYEN-HIEP-HOA' => 'Huyện Hiệp Hòa',
				'HUYEN-LANG-GIANG' => 'Huyện Lạng Giang',
				'HUYEN-LUC-NAM' => 'Huyện Lục Nam',
				'HUYEN-LUC-NGAN' => 'Huyện Lục Ngạn',
				'HUYEN-SON-DONG' => 'Huyện Sơn Động',
				'HUYEN-TAN-YEN' => 'Huyện Tân Yên',
				'HUYEN-VIET-YEN' => 'Huyện Việt Yên',
				'HUYEN-YEN-DUNG' => 'Huyện Yên Dũng',
				'HUYEN-YEN-THE' => 'Huyện Yên Thế',
			),
			'BAC-KAN' => array(
				'HUYEN-BA-BE' => 'Huyện Ba Bể',
				'THANH-PHO-BAC-KAN' => 'Thành Phố Bắc Kạn',
				'HUYEN-BACH-THONG' => 'Huyện Bạch Thông',
				'HUYEN-CHO-DON' => 'Huyện Chợ Đồn',
				'HUYEN-CHO-MOI' => 'Huyện Chợ Mới',
				'HUYEN-NA-RI' => 'Huyện Na Rì',
				'HUYEN-NGAN-SON' => 'Huyện Ngân Sơn',
				'HUYEN-PAC-NAM' => 'Huyện Pác Nặm',
			),
			'BAC-LIEU' => array(
				'THANH-PHO-BAC-LIEU' => 'Thành phố Bạc Liêu',
				'HUYEN-DONG-HAI' => 'Huyện Đông Hải',
				'THI-XA-GIA-RAI' => 'Thị xã Giá Rai',
				'HUYEN-HOA-BINH' => 'Huyện Hoà Bình',
				'HUYEN-HONG-DAN' => 'Huyện Hồng Dân',
				'HUYEN-PHUOC-LONG' => 'Huyện Phước Long',
				'HUYEN-VINH-LOI' => 'Huyện Vĩnh Lợi',
			),
			'BAC-NINH' => array(
				'THANH-PHO-BAC-NINH' => 'Thành phố Bắc Ninh',
				'HUYEN-GIA-BINH' => 'Huyện Gia Bình',
				'HUYEN-LUONG-TAI' => 'Huyện Lương Tài',
				'HUYEN-QUE-VO' => 'Huyện Quế Võ',
				'HUYEN-THUAN-THANH' => 'Huyện Thuận Thành',
				'HUYEN-TIEN-DU' => 'Huyện Tiên Du',
				'THI-XA-TU-SON' => 'Thị xã Từ Sơn',
				'HUYEN-YEN-PHONG' => 'Huyện Yên Phong',
			),
			'BEN-TRE' => array(
				'HUYEN-BA-TRI' => 'Huyện Ba Tri',
				'THANH-PHO-BEN-TRE' => 'Thành phố Bến Tre',
				'HUYEN-BINH-DAI' => 'Huyện Bình Đại',
				'HUYEN-CHAU-THANH' => 'Huyện Châu Thành',
				'HUYEN-CHO-LACH' => 'Huyện Chợ Lách',
				'HUYEN-GIONG-TROM' => 'Huyện Giồng Trôm',
				'HUYEN-MO-CAY-BAC' => 'Huyện Mỏ Cày Bắc',
				'HUYEN-MO-CAY-NAM' => 'Huyện Mỏ Cày Nam',
				'HUYEN-THANH-PHU' => 'Huyện Thạnh Phú',
			),
			'BINH-DINH' => array(
				'HUYEN-AN-LAO' => 'Huyện An Lão',
				'THI-XA-AN-NHON' => 'Thị xã An Nhơn',
				'HUYEN-HOAI-AN' => 'Huyện Hoài Ân',
				'HUYEN-HOAI-NHON' => 'Huyện Hoài Nhơn',
				'HUYEN-PHU-CAT' => 'Huyện Phù Cát',
				'HUYEN-PHU-MY' => 'Huyện Phù Mỹ',
				'THANH-PHO-QUI-NHON' => 'Thành phố Qui Nhơn',
				'HUYEN-TAY-SON' => 'Huyện Tây Sơn',
				'HUYEN-TUY-PHUOC' => 'Huyện Tuy Phước',
				'HUYEN-VAN-CANH' => 'Huyện Vân Canh',
				'HUYEN-VINH-THANH' => 'Huyện Vĩnh Thạnh',
			),
			'BINH-DUONG' => array(
				'HUYEN-BAC-TAN-UYEN' => 'Huyện Bắc Tân Uyên',
				'HUYEN-BAU-BANG' => 'Huyện Bàu Bàng',
				'THI-XA-BEN-CAT' => 'Thị xã Bến Cát',
				'HUYEN-DAU-TIENG' => 'Huyện Dầu Tiếng',
				'THI-XA-DI-AN' => 'Thị xã Dĩ An',
				'HUYEN-PHU-GIAO' => 'Huyện Phú Giáo',
				'THI-XA-TAN-UYEN' => 'Thị xã Tân Uyên',
				'THANH-PHO-THU-DAU-MOT' => 'Thành phố Thủ Dầu Một',
				'THI-XA-THUAN-AN' => 'Thị xã Thuận An',
			),
			'BINH-PHUOC' => array(
				'THI-XA-BINH-LONG' => 'Thị xã Bình Long',
				'HUYEN-BU-DANG' => 'Huyện Bù Đăng',
				'HUYEN-BU-DOP' => 'Huyện Bù Đốp',
				'HUYEN-BU-GIA-MAP' => 'Huyện Bù Gia Mập',
				'HUYEN-CHON-THANH' => 'Huyện Chơn Thành',
				'HUYEN-DONG-PHU' => 'Huyện Đồng Phú',
				'THANH-PHO-DONG-XOAI' => 'Thành phố Đồng Xoài',
				'HUYEN-HON-QUAN' => 'Huyện Hớn Quản',
				'HUYEN-LOC-NINH' => 'Huyện Lộc Ninh',
				'HUYEN-PHU-RIENG' => 'Huyện Phú Riềng',
				'THI-XA-PHUOC-LONG' => 'Thị xã Phước Long',
			),
			'BINH-THUAN' => array(
				'HUYEN-BAC-BINH' => 'Huyện Bắc Bình',
				'HUYEN-DUC-LINH' => 'Huyện Đức Linh',
				'HUYEN-HAM-TAN' => 'Huyện Hàm Tân',
				'HUYEN-HAM-THUAN-BAC' => 'Huyện Hàm Thuận Bắc',
				'HUYEN-HAM-THUAN-NAM' => 'Huyện Hàm Thuận Nam',
				'THI-XA-LA-GI' => 'Thị xã La Gi',
				'THANH-PHO-PHAN-THIET' => 'Thành phố Phan Thiết',
				'HUYEN-PHU-QUI' => 'Huyện Phú Quí',
				'HUYEN-TANH-LINH' => 'Huyện Tánh Linh',
				'HUYEN-TUY-PHONG' => 'Huyện Tuy Phong',
			),
			'CA-MAU' => array(
				'THANH-PHO-CA-MAU' => 'Thành phố Cà Mau',
				'HUYEN-CAI-NUOC' => 'Huyện Cái Nước',
				'HUYEN-DAM-DOI' => 'Huyện Đầm Dơi',
				'HUYEN-NAM-CAN' => 'Huyện Năm Căn',
				'HUYEN-NGOC-HIEN' => 'Huyện Ngọc Hiển',
				'HUYEN-PHU-TAN' => 'Huyện Phú Tân',
				'HUYEN-THOI-BINH' => 'Huyện Thới Bình',
				'HUYEN-TRAN-VAN-THOI' => 'Huyện Trần Văn Thời',
				'HUYEN-U-MINH' => 'Huyện U Minh',
			),
			'CAN-THO' => array(
				'QUAN-BINH-THUY' => 'Quận Bình Thuỷ',
				'QUAN-CAI-RANG' => 'Quận Cái Răng',
				'HUYEN-CO-DO' => 'Huyện Cờ Đỏ',
				'QUAN-NINH-KIEU' => 'Quận Ninh Kiều',
				'QUAN-O-MON' => 'Quận Ô Môn',
				'HUYEN-PHONG-DIEN' => 'Huyện Phong Điền',
				'HUYEN-THOI-LAI' => 'Huyện Thới Lai',
				'QUAN-THOT-NOT' => 'Quận Thốt Nốt',
				'HUYEN-VINH-THANH' => 'Huyện Vĩnh Thạnh',
			),
			'CAO-BANG' => array(
				'HUYEN-BAO-LAC' => 'Huyện Bảo Lạc',
				'HUYEN-BAO-LAM' => 'Huyện Bảo Lâm',
				'THANH-PHO-CAO-BANG' => 'Thành phố Cao Bằng',
				'HUYEN-HA-LANG' => 'Huyện Hạ Lang',
				'HUYEN-HA-QUANG' => 'Huyện Hà Quảng',
				'HUYEN-HOA-AN' => 'Huyện Hoà An',
				'HUYEN-NGUYEN-BINH' => 'Huyện Nguyên Bình',
				'HUYEN-PHUC-HOA' => 'Huyện Phục Hoà',
				'HUYEN-QUANG-UYEN' => 'Huyện Quảng Uyên',
				'HUYEN-THACH-AN' => 'Huyện Thạch An',
				'HUYEN-THONG-NONG' => 'Huyện Thông Nông',
				'HUYEN-TRA-LINH' => 'Huyện Trà Lĩnh',
				'HUYEN-TRUNG-KHANH' => 'Huyện Trùng Khánh',
			),
			'DA-NANG' => array(
				'QUAN-CAM-LE' => 'Quận Cẩm Lệ',
				'QUAN-HAI-CHAU' => 'Quận Hải Châu',
				'HUYEN-HOA-VANG' => 'Huyện Hòa Vang',
				'HUYEN-HOANG-SA' => 'Huyện Hoàng Sa',
				'QUAN-LIEN-CHIEU' => 'Quận Liên Chiểu',
				'QUAN-NGU-HANH-SON' => 'Quận Ngũ Hành Sơn',
				'QUAN-SON-TRA' => 'Quận Sơn Trà',
				'QUAN-THANH-KHE' => 'Quận Thanh Khê',
			),
			'DAK-LAK' => array(
				'HUYEN-BUON-DON' => 'Huyện Buôn Đôn',
				'THI-XA-BUON-HO' => 'Thị Xã Buôn Hồ',
				'THANH-PHO-BUON-MA-THUOT' => 'Thành phố Buôn Ma Thuột',
				'HUYEN-CU-KUIN' => 'Huyện Cư Kuin',
				'HUYEN-CU-MGAR' => "Huyện Cư M'gar",
				'HUYEN-EA-HLEO' => 'Huyện Ea H\'leo',
				'HUYEN-EA-KAR' => 'Huyện Ea Kar',
				'HUYEN-EA-SUP' => 'Huyện Ea Súp',
				'HUYEN-KRONG-A-NA' => 'Huyện Krông A Na',
				'HUYEN-KRONG-BONG' => 'Huyện Krông Bông',
				'HUYEN-KRONG-BUK' => 'Huyện Krông Búk',
				'HUYEN-KRONG-NANG' => 'Huyện Krông Năng',
				'HUYEN-KRONG-PAC' => 'Huyện Krông Pắc',
				'HUYEN-LAK' => 'Huyện Lắk',
				'HUYEN-MDRAK' => 'Huyện M\'Đrắk',
			),
			'DAK-NONG' => array(
				'HUYEN-CU-JUT' => 'Huyện Cư Jút',
				'HUYEN-DAK-GLONG' => 'Huyện Đăk Glong',
				'HUYEN-DAK-MIL' => 'Huyện Đắk Mil',
				'HUYEN-DAK-RLAP' => 'Huyện Đắk R\'Lấp',
				'HUYEN-DAK-SONG' => 'Huyện Đắk Song',
				'THI-XA-GIA-NGHIA' => 'Thị xã Gia Nghĩa',
				'HUYEN-KRONG-NO' => 'Huyện Krông Nô',
				'HUYEN-TUY-DUC' => 'Huyện Tuy Đức',
			),
			'DIEN-BIEN' => array(
				'HUYEN-DIEN-BIEN' => 'Huyện Điện Biên',
				'HUYEN-DIEN-BIEN-DONG' => 'Huyện Điện Biên Đông',
				'THANH-PHO-DIEN-BIEN-PHU' => 'Thành phố Điện Biên Phủ',
				'HUYEN-MUONG-ANG' => 'Huyện Mường Ảng',
				'HUYEN-MUONG-CHA' => 'Huyện Mường Chà',
				'THI-XA-MUONG-LAY' => 'Thị Xã Mường Lay',
				'HUYEN-MUONG-NHE' => 'Huyện Mường Nhé',
				'HUYEN-NAM-PO' => 'Huyện Nậm Pồ',
				'HUYEN-TUA-CHUA' => 'Huyện Tủa Chùa',
				'HUYEN-TUAN-GIAO' => 'Huyện Tuần Giáo',
			),
			'DONG-NAI' => array(
				'THANH-PHO-BIEN-HOA' => 'Thành phố Biên Hòa',
				'HUYEN-CAM-MY' => 'Huyện Cẩm Mỹ',
				'HUYEN-DINH-QUAN' => 'Huyện Định Quán',
				'THANH-PHO-LONG-KHANH' => 'Thành phố Long Khánh',
				'HUYEN-LONG-THANH' => 'Huyện Long Thành',
				'HUYEN-NHON-TRACH' => 'Huyện Nhơn Trạch',
				'HUYEN-TAN-PHU' => 'Huyện Tân Phú',
				'HUYEN-THONG-NHAT' => 'Huyện Thống Nhất',
				'HUYEN-TRANG-BOM' => 'Huyện Trảng Bom',
				'HUYEN-VINH-CUU' => 'Huyện Vĩnh Cửu',
				'HUYEN-XUAN-LOC' => 'Huyện Xuân Lộc',
			),
			'DONG-THAP' => array(
				'THANH-PHO-CAO-LANH' => 'Thành phố Cao Lãnh',
				'HUYEN-CAO-LANH' => 'Huyện Cao Lãnh',
				'HUYEN-CHAU-THANH' => 'Huyện Châu Thành',
				'THI-XA-HONG-NGU' => 'Thị xã Hồng Ngự',
				'HUYEN-HONG-NGU' => 'Huyện Hồng Ngự',
				'HUYEN-LAI-VUNG' => 'Huyện Lai Vung',
				'HUYEN-LAP-VO' => 'Huyện Lấp Vò',
				'THANH-PHO-SA-DEC' => 'Thành phố Sa Đéc',
				'HUYEN-TAM-NONG' => 'Huyện Tam Nông',
				'HUYEN-TAN-HONG' => 'Huyện Tân Hồng',
				'HUYEN-THANH-BINH' => 'Huyện Thanh Bình',
				'HUYEN-THAP-MUOI' => 'Huyện Tháp Mười',
			),
			'GIA-LAI' => array(
				'THI-XA-AN-KHE' => 'Thị xã An Khê',
				'THI-XA-AYUN-PA' => 'Thị xã Ayun Pa',
				'HUYEN-CHU-PAH' => 'Huyện Chư Păh',
				'HUYEN-CHU-PRONG' => 'Huyện Chư Prông',
				'HUYEN-CHU-PUH' => 'Huyện Chư Pưh',
				'HUYEN-CHU-SE' => 'Huyện Chư Sê',
				'HUYEN-DAK-DOA' => 'Huyện Đăk Đoa',
				'HUYEN-DAK-PO' => 'Huyện Đăk Pơ',
				'HUYEN-DUC-CO' => 'Huyện Đức Cơ',
				'HUYEN-IA-GRAI' => 'Huyện Ia Grai',
				'HUYEN-IA-PA' => 'Huyện Ia Pa',
				'HUYEN-KBANG' => 'Huyện KBang',
				'HUYEN-KONG-CHRO' => 'Huyện Kông Chro',
				'HUYEN-KRONG-PA' => 'Huyện Krông Pa',
				'HUYEN-MANG-YANG' => 'Huyện Mang Yang',
				'HUYEN-PHU-THIEN' => 'Huyện Phú Thiện',
				'THANH-PHO-PLEIKU' => 'Thành phố Pleiku',
			),
			'HA-GIANG' => array(
				'HUYEN-BAC-ME' => 'Huyện Bắc Mê',
				'HUYEN-BAC-QUANG' => 'Huyện Bắc Quang',
				'HUYEN-DONG-VAN' => 'Huyện Đồng Văn',
				'THANH-PHO-HA-GIANG' => 'Thành phố Hà Giang',
				'HUYEN-HOANG-SU-PHI' => 'Huyện Hoàng Su Phì',
				'HUYEN-MEO-VAC' => 'Huyện Mèo Vạc',
				'HUYEN-QUAN-BA' => 'Huyện Quản Bạ',
				'HUYEN-QUANG-BINH' => 'Huyện Quang Bình',
				'HUYEN-VI-XUYEN' => 'Huyện Vị Xuyên',
				'HUYEN-XIN-MAN' => 'Huyện Xín Mần',
				'HUYEN-YEN-MINH' => 'Huyện Yên Minh',
			),
			'HA-NAM' => array(
				'HUYEN-BINH-LUC' => 'Huyện Bình Lục',
				'HUYEN-DUY-TIEN' => 'Huyện Duy Tiên',
				'HUYEN-KIM-BANG' => 'Huyện Kim Bảng',
				'HUYEN-LY-NHAN' => 'Huyện Lý Nhân',
				'THANH-PHO-PHU-LY' => 'Thành phố Phủ Lý',
				'HUYEN-THANH-LIEM' => 'Huyện Thanh Liêm',
			),
			'HA-NOI' => array(
				'QUAN-BA-DINH' => 'Quận Ba Đình',
				'HUYEN-BA-VI' => 'Huyện Ba Vì',
				'QUAN-BAC-TU-LIEM' => 'Quận Bắc Từ Liêm',
				'QUAN-CAU-GIAY' => 'Quận Cầu Giấy',
				'HUYEN-CHUONG-MY' => 'Huyện Chương Mỹ',
				'HUYEN-DAN-PHUONG' => 'Huyện Đan Phượng',
				'HUYEN-DONG-ANH' => 'Huyện Đông Anh',
				'QUAN-DONG-DA' => 'Quận Đống Đa',
				'HUYEN-GIA-LAM' => 'Huyện Gia Lâm',
				'QUAN-HA-DONG' => 'Quận Hà Đông',
				'QUAN-HAI-BA-TRUNG' => 'Quận Hai Bà Trưng',
				'HUYEN-HOAI-DUC' => 'Huyện Hoài Đức',
				'QUAN-HOAN-KIEM' => 'Quận Hoàn Kiếm',
				'QUAN-HOANG-MAI' => 'Quận Hoàng Mai',
				'QUAN-LONG-BIEN' => 'Quận Long Biên',
				'HUYEN-ME-LINH' => 'Huyện Mê Linh',
				'HUYEN-MY-DUC' => 'Huyện Mỹ Đức',
				'QUAN-NAM-TU-LIEM' => 'Quận Nam Từ Liêm',
				'HUYEN-PHU-XUYEN' => 'Huyện Phú Xuyên',
				'HUYEN-PHUC-THO' => 'Huyện Phúc Thọ',
				'HUYEN-QUOC-OAI' => 'Huyện Quốc Oai',
				'HUYEN-SOC-SON' => 'Huyện Sóc Sơn',
				'THI-XA-SON-TAY' => 'Thị xã Sơn Tây',
				'QUAN-TAY-HO' => 'Quận Tây Hồ',
				'HUYEN-THACH-THAT' => 'Huyện Thạch Thất',
				'HUYEN-THANH-OAI' => 'Huyện Thanh Oai',
				'HUYEN-THANH-TRI' => 'Huyện Thanh Trì',
				'QUAN-THANH-XUAN' => 'Quận Thanh Xuân',
				'HUYEN-THUONG-TIN' => 'Huyện Thường Tín',
				'HUYEN-UNG-HOA' => 'Huyện Ứng Hòa',
			),
			'HA-TINH' => array(
				'HUYEN-CAM-XUYEN' => 'Huyện Cẩm Xuyên',
				'HUYEN-CAN-LOC' => 'Huyện Can Lộc',
				'HUYEN-DUC-THO' => 'Huyện Đức Thọ',
				'THANH-PHO-HA-TINH' => 'Thành phố Hà Tĩnh',
				'THI-XA-HONG-LINH' => 'Thị xã Hồng Lĩnh',
				'HUYEN-HUONG-KHE' => 'Huyện Hương Khê',
				'HUYEN-HUONG-SON' => 'Huyện Hương Sơn',
				'HUYEN-KY-ANH' => 'Huyện Kỳ Anh',
				'THI-XA-KY-ANH' => 'Thị xã Kỳ Anh',
				'HUYEN-LOC-HA' => 'Huyện Lộc Hà',
				'HUYEN-NGHI-XUAN' => 'Huyện Nghi Xuân',
				'HUYEN-THACH-HA' => 'Huyện Thạch Hà',
				'HUYEN-VU-QUANG' => 'Huyện Vũ Quang',
			),
			'HAI-DUONG' => array(
				'HUYEN-BINH-GIANG' => 'Huyện Bình Giang',
				'HUYEN-CAM-GIANG' => 'Huyện Cẩm Giàng',
				'THANH-PHO-CHI-LINH' => 'Thành phố Chí Linh',
				'HUYEN-GIA-LOC' => 'Huyện Gia Lộc',
				'THANH-PHO-HAI-DUONG' => 'Thành phố Hải Dương',
				'HUYEN-KIM-THANH' => 'Huyện Kim Thành',
				'THI-XA-KINH-MON' => 'Thị xã Kinh Môn',
				'HUYEN-NAM-SACH' => 'Huyện Nam Sách',
				'HUYEN-NINH-GIANG' => 'Huyện Ninh Giang',
				'HUYEN-THANH-HA' => 'Huyện Thanh Hà',
				'HUYEN-THANH-MIEN' => 'Huyện Thanh Miện',
				'HUYEN-TU-KY' => 'Huyện Tứ Kỳ',
			),
			'HAI-PHONG' => array(
				'HUYEN-AN-DUONG' => 'Huyện An Dương',
				'HUYEN-AN-LAO' => 'Huyện An Lão',
				'HUYEN-BACH-LONG-VI' => 'Huyện Bạch Long Vĩ',
				'HUYEN-CAT-HAI' => 'Huyện Cát Hải',
				'QUAN-DO-SON' => 'Quận Đồ Sơn',
				'QUAN-DUONG-KINH' => 'Quận Dương Kinh',
				'QUAN-HAI-AN' => 'Quận Hải An',
				'QUAN-HONG-BANG' => 'Quận Hồng Bàng',
				'QUAN-KIEN-AN' => 'Quận Kiến An',
				'HUYEN-KIEN-THUY' => 'Huyện Kiến Thuỵ',
				'QUAN-LE-CHAN' => 'Quận Lê Chân',
				'QUAN-NGO-QUYEN' => 'Quận Ngô Quyền',
				'HUYEN-THUY-NGUYEN' => 'Huyện Thuỷ Nguyên',
				'HUYEN-TIEN-LANG' => 'Huyện Tiên Lãng',
				'HUYEN-VINH-BAO' => 'Huyện Vĩnh Bảo',
			),
			'HAU-GIANG' => array(
				'HUYEN-CHAU-THANH' => 'Huyện Châu Thành',
				'HUYEN-CHAU-THANH-A' => 'Huyện Châu Thành A',
				'HUYEN-LONG-MY' => 'Huyện Long Mỹ',
				'THI-XA-LONG-MY' => 'Thị xã Long Mỹ',
				'THI-XA-NGA-BAY' => 'Thị xã Ngã Bảy',
				'HUYEN-PHUNG-HIEP' => 'Huyện Phụng Hiệp',
				'THANH-PHO-VI-THANH' => 'Thành phố Vị Thanh',
				'HUYEN-VI-THUY' => 'Huyện Vị Thuỷ',
			),
			'HO-CHI-MINH' => array(
				'QUAN-1' => 'Quận 1',
				'QUAN-2' => 'Quận 2',
				'QUAN-3' => 'Quận 3',
				'QUAN-4' => 'Quận 4',
				'QUAN-5' => 'Quận 5',
				'QUAN-6' => 'Quận 6',
				'QUAN-7' => 'Quận 7',
				'QUAN-8' => 'Quận 8',
				'QUAN-9' => 'Quận 9',
				'QUAN-10' => 'Quận 10',
				'QUAN-11' => 'Quận 11',
				'QUAN-12' => 'Quận 12',
				'HUYEN-BINH-CHANH' => 'Huyện Bình Chánh',
				'QUAN-BINH-TAN' => 'Quận Bình Tân',
				'QUAN-BINH-THANH' => 'Quận Bình Thạnh',
				'HUYEN-CAN-GIO' => 'Huyện Cần Giờ',
				'HUYEN-CU-CHI' => 'Huyện Củ Chi',
				'QUAN-GO-VAP' => 'Quận Gò Vấp',
				'HUYEN-HOC-MON' => 'Huyện Hóc Môn',
				'HUYEN-NHA-BE' => 'Huyện Nhà Bè',
				'QUAN-PHU-NHUAN' => 'Quận Phú Nhuận',
				'QUAN-TAN-BINH' => 'Quận Tân Bình',
				'QUAN-TAN-PHU' => 'Quận Tân Phú',
				'QUAN-THU-DUC' => 'Quận Thủ Đức',
			),
			'HOA-BINH' => array(
				'HUYEN-CAO-PHONG' => 'Huyện Cao Phong',
				'HUYEN-DA-BAC' => 'Huyện Đà Bắc',
				'THANH-PHO-HOA-BINH' => 'Thành phố Hòa Bình',
				'HUYEN-KIM-BOI' => 'Huyện Kim Bôi',
				'HUYEN-KY-SON' => 'Huyện Kỳ Sơn',
				'HUYEN-LAC-SON' => 'Huyện Lạc Sơn',
				'HUYEN-LAC-THUY' => 'Huyện Lạc Thủy',
				'HUYEN-LUONG-SON' => 'Huyện Lương Sơn',
				'HUYEN-MAI-CHAU' => 'Huyện Mai Châu',
				'HUYEN-TAN-LAC' => 'Huyện Tân Lạc',
				'HUYEN-YEN-THUY' => 'Huyện Yên Thủy',
			),
			'HUNG-YEN' => array(
				'HUYEN-AN-THI' => 'Huyện Ân Thi',
				'THANH-PHO-HUNG-YEN' => 'Thành phố Hưng Yên',
				'HUYEN-KHOAI-CHAU' => 'Huyện Khoái Châu',
				'HUYEN-KIM-DONG' => 'Huyện Kim Động',
				'THI-XA-MY-HAO' => 'Thị xã Mỹ Hào',
				'HUYEN-PHU-CU' => 'Huyện Phù Cừ',
				'HUYEN-TIEN-LU' => 'Huyện Tiên Lữ',
				'HUYEN-VAN-GIANG' => 'Huyện Văn Giang',
				'HUYEN-VAN-LAM' => 'Huyện Văn Lâm',
				'HUYEN-YEN-MY' => 'Huyện Yên Mỹ',
			),
			'KHANH-HOA' => array(
				'HUYEN-CAM-LAM' => 'Huyện Cam Lâm',
				'THANH-PHO-CAM-RANH' => 'Thành phố Cam Ranh',
				'HUYEN-DIEN-KHANH' => 'Huyện Diên Khánh',
				'HUYEN-KHANH-SON' => 'Huyện Khánh Sơn',
				'HUYEN-KHANH-VINH' => 'Huyện Khánh Vĩnh',
				'THANH-PHO-NHA-TRANG' => 'Thành phố Nha Trang',
				'THI-XA-NINH-HOA' => 'Thị xã Ninh Hòa',
				'HUYEN-TRUONG-SA' => 'Huyện Trường Sa',
				'HUYEN-VAN-NINH' => 'Huyện Vạn Ninh',
			),
			'KIEN-GIANG' => array(
				'HUYEN-AN-BIEN' => 'Huyện An Biên',
				'HUYEN-AN-MINH' => 'Huyện An Minh',
				'HUYEN-CHAU-THANH' => 'Huyện Châu Thành',
				'HUYEN-GIANG-THANH' => 'Huyện Giang Thành',
				'HUYEN-GIONG-RIENG' => 'Huyện Giồng Riềng',
				'HUYEN-GO-QUAO' => 'Huyện Gò Quao',
				'THANH-PHO-HA-TIEN' => 'Thành phố Hà Tiên',
				'HUYEN-HON-DAT' => 'Huyện Hòn Đất',
				'HUYEN-KIEN-HAI' => 'Huyện Kiên Hải',
				'HUYEN-KIEN-LUONG' => 'Huyện Kiên Lương',
				'HUYEN-PHU-QUOC' => 'Huyện Phú Quốc',
				'THANH-PHO-RACH-GIA' => 'Thành phố Rạch Giá',
				'HUYEN-TAN-HIEP' => 'Huyện Tân Hiệp',
				'HUYEN-U-MINH-THUONG' => 'Huyện U Minh Thượng',
				'HUYEN-VINH-THUAN' => 'Huyện Vĩnh Thuận',
			),
			'KON-TUM' => array(
				'HUYEN-DAK-GLEI' => 'Huyện Đắk Glei',
				'HUYEN-DAK-HA' => 'Huyện Đắk Hà',
				'HUYEN-DAK-TO' => 'Huyện Đắk Tô',
				'HUYEN-IA-H-DRAI' => 'Huyện Ia H\' Drai',
				'HUYEN-KON-PLONG' => 'Huyện Kon Plông',
				'HUYEN-KON-RAY' => 'Huyện Kon Rẫy',
				'THANH-PHO-KON-TUM' => 'Thành phố Kon Tum',
				'HUYEN-NGOC-HOI' => 'Huyện Ngọc Hồi',
				'HUYEN-SA-THAY' => 'Huyện Sa Thầy',
				'HUYEN-TU-MO-RONG' => 'Huyện Tu Mơ Rông',
			),
			'LAI-CHAU' => array(
				'THANH-PHO-LAI-CHAU' => 'Thành phố Lai Châu',
				'HUYEN-MUONG-TE' => 'Huyện Mường Tè',
				'HUYEN-NAM-NHUN' => 'Huyện Nậm Nhùn',
				'HUYEN-PHONG-THO' => 'Huyện Phong Thổ',
				'HUYEN-SIN-HO' => 'Huyện Sìn Hồ',
				'HUYEN-TAM-DUONG' => 'Huyện Tam Đường',
				'HUYEN-TAN-UYEN' => 'Huyện Tân Uyên',
				'HUYEN-THAN-UYEN' => 'Huyện Than Uyên',
			),
			'LAM-DONG' => array(
				'HUYEN-BAO-LAM' => 'Huyện Bảo Lâm',
				'THANH-PHO-BAO-LOC' => 'Thành phố Bảo Lộc',
				'HUYEN-CAT-TIEN' => 'Huyện Cát Tiên',
				'HUYEN-DA-HUOAI' => 'Huyện Đạ Huoai',
				'THANH-PHO-DA-LAT' => 'Thành phố Đà Lạt',
				'HUYEN-DA-TEH' => 'Huyện Đạ Tẻh',
				'HUYEN-DAM-RONG' => 'Huyện Đam Rông',
				'HUYEN-DI-LINH' => 'Huyện Di Linh',
				'HUYEN-DON-DUONG' => 'Huyện Đơn Dương',
				'HUYEN-DUC-TRONG' => 'Huyện Đức Trọng',
				'HUYEN-LAC-DUONG' => 'Huyện Lạc Dương',
				'HUYEN-LAM-HA' => 'Huyện Lâm Hà',
			),
			'LANG-SON' => array(
				'HUYEN-BAC-SON' => 'Huyện Bắc Sơn',
				'HUYEN-BINH-GIA' => 'Huyện Bình Gia',
				'HUYEN-CAO-LOC' => 'Huyện Cao Lộc',
				'HUYEN-CHI-LANG' => 'Huyện Chi Lăng',
				'HUYEN-DINH-LAP' => 'Huyện Đình Lập',
				'HUYEN-HUU-LUNG' => 'Huyện Hữu Lũng',
				'THANH-PHO-LANG-SON' => 'Thành phố Lạng Sơn',
				'HUYEN-LOC-BINH' => 'Huyện Lộc Bình',
				'HUYEN-TRANG-DINH' => 'Huyện Tràng Định',
				'HUYEN-VAN-LANG' => 'Huyện Văn Lãng',
				'HUYEN-VAN-QUAN' => 'Huyện Văn Quan',
			),
			'LAO-CAI' => array(
				'HUYEN-BAC-HA' => 'Huyện Bắc Hà',
				'HUYEN-BAO-THANG' => 'Huyện Bảo Thắng',
				'HUYEN-BAO-YEN' => 'Huyện Bảo Yên',
				'HUYEN-BAT-XAT' => 'Huyện Bát Xát',
				'THANH-PHO-LAO-CAI' => 'Thành phố Lào Cai',
				'HUYEN-MUONG-KHUONG' => 'Huyện Mường Khương',
				'THI-XA-SA-PA' => 'Thị xã Sa Pa',
				'HUYEN-SI-MA-CAI' => 'Huyện Si Ma Cai',
				'HUYEN-VAN-BAN' => 'Huyện Văn Bàn',
			),
			'LONG-AN' => array(
				'HUYEN-BEN-LUC' => 'Huyện Bến Lức',
				'HUYEN-CAN-DUOC' => 'Huyện Cần Đước',
				'HUYEN-CAN-GIUOC' => 'Huyện Cần Giuộc',
				'HUYEN-CHAU-THANH' => 'Huyện Châu Thành',
				'HUYEN-DUC-HOA' => 'Huyện Đức Hòa',
				'HUYEN-DUC-HUE' => 'Huyện Đức Huệ',
				'THI-XA-KIEN-TUONG' => 'Thị xã Kiến Tường',
				'HUYEN-MOC-HOA' => 'Huyện Mộc Hóa',
				'THANH-PHO-TAN-AN' => 'Thành phố Tân An',
				'HUYEN-TAN-HUNG' => 'Huyện Tân Hưng',
				'HUYEN-TAN-THANH' => 'Huyện Tân Thạnh',
				'HUYEN-TAN-TRU' => 'Huyện Tân Trụ',
				'HUYEN-THANH-HOA' => 'Huyện Thạnh Hóa',
				'HUYEN-THU-THUA' => 'Huyện Thủ Thừa',
				'HUYEN-VINH-HUNG' => 'Huyện Vĩnh Hưng',
			),
			'NAM-DINH' => array(
				'HUYEN-GIAO-THUY' => 'Huyện Giao Thủy',
				'HUYEN-HAI-HAU' => 'Huyện Hải Hậu',
				'HUYEN-MY-LOC' => 'Huyện Mỹ Lộc',
				'THANH-PHO-NAM-DINH' => 'Thành phố Nam Định',
				'HUYEN-NAM-TRUC' => 'Huyện Nam Trực',
				'HUYEN-NGHIA-HUNG' => 'Huyện Nghĩa Hưng',
				'HUYEN-TRUC-NINH' => 'Huyện Trực Ninh',
				'HUYEN-VU-BAN' => 'Huyện Vụ Bản',
				'HUYEN-XUAN-TRUONG' => 'Huyện Xuân Trường',
				'HUYEN-Y-YEN' => 'Huyện Ý Yên',
			),
			'NGHE-AN' => array(
				'HUYEN-ANH-SON' => 'Huyện Anh Sơn',
				'HUYEN-CON-CUONG' => 'Huyện Con Cuông',
				'THI-XA-CUA-LO' => 'Thị xã Cửa Lò',
				'HUYEN-DIEN-CHAU' => 'Huyện Diễn Châu',
				'HUYEN-DO-LUONG' => 'Huyện Đô Lương',
				'THI-XA-HOANG-MAI' => 'Thị xã Hoàng Mai',
				'HUYEN-HUNG-NGUYEN' => 'Huyện Hưng Nguyên',
				'HUYEN-KY-SON' => 'Huyện Kỳ Sơn',
				'HUYEN-NAM-DAN' => 'Huyện Nam Đàn',
				'HUYEN-NGHI-LOC' => 'Huyện Nghi Lộc',
				'HUYEN-NGHIA-DAN' => 'Huyện Nghĩa Đàn',
				'HUYEN-QUE-PHONG' => 'Huyện Quế Phong',
				'HUYEN-QUY-CHAU' => 'Huyện Quỳ Châu',
				'HUYEN-QUY-HOP' => 'Huyện Quỳ Hợp',
				'HUYEN-QUYNH-LUU' => 'Huyện Quỳnh Lưu',
				'HUYEN-TAN-KY' => 'Huyện Tân Kỳ',
				'THI-XA-THAI-HOA' => 'Thị xã Thái Hoà',
				'HUYEN-THANH-CHUONG' => 'Huyện Thanh Chương',
				'HUYEN-TUONG-DUONG' => 'Huyện Tương Dương',
				'THANH-PHO-VINH' => 'Thành phố Vinh',
				'HUYEN-YEN-THANH' => 'Huyện Yên Thành',
			),
			'NINH-BINH' => array(
				'HUYEN-GIA-VIEN' => 'Huyện Gia Viễn',
				'HUYEN-HOA-LU' => 'Huyện Hoa Lư',
				'HUYEN-KIM-SON' => 'Huyện Kim Sơn',
				'HUYEN-NHO-QUAN' => 'Huyện Nho Quan',
				'THANH-PHO-NINH-BINH' => 'Thành phố Ninh Bình',
				'THANH-PHO-TAM-DIEP' => 'Thành phố Tam Điệp',
				'HUYEN-YEN-KHANH' => 'Huyện Yên Khánh',
				'HUYEN-YEN-MO' => 'Huyện Yên Mô',
			),
			'NINH-THUAN' => array(
				'HUYEN-BAC-AI' => 'Huyện Bác Ái',
				'HUYEN-NINH-HAI' => 'Huyện Ninh Hải',
				'HUYEN-NINH-PHUOC' => 'Huyện Ninh Phước',
				'HUYEN-NINH-SON' => 'Huyện Ninh Sơn',
				'THANH-PHO-PHAN-RANG-THAP-CHAM' => 'Thành phố Phan Rang-Tháp Chàm',
				'HUYEN-THUAN-BAC' => 'Huyện Thuận Bắc',
				'HUYEN-THUAN-NAM' => 'Huyện Thuận Nam',
			),
			'PHU-THO' => array(
				'HUYEN-CAM-KHE' => 'Huyện Cẩm Khê',
				'HUYEN-DOAN-HUNG' => 'Huyện Đoan Hùng',
				'HUYEN-HA-HOA' => 'Huyện Hạ Hoà',
				'HUYEN-LAM-THAO' => 'Huyện Lâm Thao',
				'HUYEN-PHU-NINH' => 'Huyện Phù Ninh',
				'THI-XA-PHU-THO' => 'Thị xã Phú Thọ',
				'HUYEN-TAM-NONG' => 'Huyện Tam Nông',
				'HUYEN-TAN-SON' => 'Huyện Tân Sơn',
				'HUYEN-THANH-BA' => 'Huyện Thanh Ba',
				'HUYEN-THANH-SON' => 'Huyện Thanh Sơn',
				'HUYEN-THANH-THUY' => 'Huyện Thanh Thuỷ',
				'THANH-PHO-VIET-TRI' => 'Thành phố Việt Trì',
				'HUYEN-YEN-LAP' => 'Huyện Yên Lập',
			),
			'PHU-YEN' => array(
				'HUYEN-DONG-HOA' => 'Huyện Đông Hòa',
				'HUYEN-DONG-XUAN' => 'Huyện Đồng Xuân',
				'HUYEN-PHU-HOA' => 'Huyện Phú Hoà',
				'HUYEN-SON-HOA' => 'Huyện Sơn Hòa',
				'THI-XA-SONG-CAU' => 'Thị xã Sông Cầu',
				'HUYEN-SONG-HINH' => 'Huyện Sông Hinh',
				'HUYEN-TAY-HOA' => 'Huyện Tây Hoà',
				'HUYEN-TUY-AN' => 'Huyện Tuy An',
				'THANH-PHO-TUY-HOA' => 'Thành phố Tuy Hoà',
			),
			'QUANG-BINH' => array(
				'THI-XA-BA-DON' => 'Thị xã Ba Đồn',
				'HUYEN-BO-TRACH' => 'Huyện Bố Trạch',
				'THANH-PHO-DONG-HOI' => 'Thành Phố Đồng Hới',
				'HUYEN-LE-THUY' => 'Huyện Lệ Thủy',
				'HUYEN-MINH-HOA' => 'Huyện Minh Hóa',
				'HUYEN-QUANG-NINH' => 'Huyện Quảng Ninh',
				'HUYEN-QUANG-TRACH' => 'Huyện Quảng Trạch',
				'HUYEN-TUYEN-HOA' => 'Huyện Tuyên Hóa',
			),
			'QUANG-NAM' => array(
				'HUYEN-BAC-TRA-MY' => 'Huyện Bắc Trà My',
				'HUYEN-DAI-LOC' => 'Huyện Đại Lộc',
				'THI-XA-DIEN-BAN' => 'Thị xã Điện Bàn',
				'HUYEN-DONG-GIANG' => 'Huyện Đông Giang',
				'HUYEN-DUY-XUYEN' => 'Huyện Duy Xuyên',
				'HUYEN-HIEP-DUC' => 'Huyện Hiệp Đức',
				'THANH-PHO-HOI-AN' => 'Thành phố Hội An',
				'HUYEN-NAM-GIANG' => 'Huyện Nam Giang',
				'HUYEN-NAM-TRA-MY' => 'Huyện Nam Trà My',
				'HUYEN-NONG-SON' => 'Huyện Nông Sơn',
				'HUYEN-NUI-THANH' => 'Huyện Núi Thành',
				'HUYEN-PHU-NINH' => 'Huyện Phú Ninh',
				'HUYEN-PHUOC-SON' => 'Huyện Phước Sơn',
				'HUYEN-QUE-SON' => 'Huyện Quế Sơn',
				'THANH-PHO-TAM-KY' => 'Thành phố Tam Kỳ',
				'HUYEN-TAY-GIANG' => 'Huyện Tây Giang',
				'HUYEN-THANG-BINH' => 'Huyện Thăng Bình',
				'HUYEN-TIEN-PHUOC' => 'Huyện Tiên Phước',
			),
			'QUANG-NGAI' => array(
				'HUYEN-BA-TO' => 'Huyện Ba Tơ',
				'HUYEN-BINH-SON' => 'Huyện Bình Sơn',
				'HUYEN-DUC-PHO' => 'Huyện Đức Phổ',
				'HUYEN-LY-SON' => 'Huyện Lý Sơn',
				'HUYEN-MINH-LONG' => 'Huyện Minh Long',
				'HUYEN-MO-DUC' => 'Huyện Mộ Đức',
				'HUYEN-NGHIA-HANH' => 'Huyện Nghĩa Hành',
				'THANH-PHO-QUANG-NGAI' => 'Thành phố Quảng Ngãi',
				'HUYEN-SON-HA' => 'Huyện Sơn Hà',
				'HUYEN-SON-TAY' => 'Huyện Sơn Tây',
				'HUYEN-SON-TINH' => 'Huyện Sơn Tịnh',
				'HUYEN-TAY-TRA' => 'Huyện Tây Trà',
				'HUYEN-TRA-BONG' => 'Huyện Trà Bồng',
				'HUYEN-TU-NGHIA' => 'Huyện Tư Nghĩa',
			),
			'QUANG-NINH' => array(
				'HUYEN-BA-CHE' => 'Huyện Ba Chẽ',
				'HUYEN-BINH-LIEU' => 'Huyện Bình Liêu',
				'THANH-PHO-CAM-PHA' => 'Thành phố Cẩm Phả',
				'HUYEN-CO-TO' => 'Huyện Cô Tô',
				'HUYEN-DAM-HA' => 'Huyện Đầm Hà',
				'THI-XA-DONG-TRIEU' => 'Thị xã Đông Triều',
				'THANH-PHO-HA-LONG' => 'Thành phố Hạ Long',
				'HUYEN-HAI-HA' => 'Huyện Hải Hà',
				'HUYEN-HOANH-BO' => 'Huyện Hoành Bồ',
				'THANH-PHO-MONG-CAI' => 'Thành phố Móng Cái',
				'THI-XA-QUANG-YEN' => 'Thị xã Quảng Yên',
				'HUYEN-TIEN-YEN' => 'Huyện Tiên Yên',
				'THANH-PHO-UONG-BI' => 'Thành phố Uông Bí',
				'HUYEN-VAN-DON' => 'Huyện Vân Đồn',
			),
			'QUANG-TRI' => array(
				'HUYEN-CAM-LO' => 'Huyện Cam Lộ',
				'HUYEN-CON-CO' => 'Huyện Cồn Cỏ',
				'HUYEN-DA-KRONG' => 'Huyện Đa Krông',
				'THANH-PHO-DONG-HA' => 'Thành phố Đông Hà',
				'HUYEN-GIO-LINH' => 'Huyện Gio Linh',
				'HUYEN-HAI-LANG' => 'Huyện Hải Lăng',
				'HUYEN-HUONG-HOA' => 'Huyện Hướng Hóa',
				'THI-XA-QUANG-TRI' => 'Thị xã Quảng Trị',
				'HUYEN-TRIEU-PHONG' => 'Huyện Triệu Phong',
				'HUYEN-VINH-LINH' => 'Huyện Vĩnh Linh',
			),
			'SOC-TRANG' => array(
				'HUYEN-CHAU-THANH' => 'Huyện Châu Thành',
				'HUYEN-CU-LAO-DUNG' => 'Huyện Cù Lao Dung',
				'HUYEN-KE-SACH' => 'Huyện Kế Sách',
				'HUYEN-LONG-PHU' => 'Huyện Long Phú',
				'HUYEN-MY-TU' => 'Huyện Mỹ Tú',
				'HUYEN-MY-XUYEN' => 'Huyện Mỹ Xuyên',
				'THI-XA-NGA-NAM' => 'Thị xã Ngã Năm',
				'THANH-PHO-SOC-TRANG' => 'Thành phố Sóc Trăng',
				'HUYEN-THANH-TRI' => 'Huyện Thạnh Trị',
				'HUYEN-TRAN-DE' => 'Huyện Trần Đề',
				'THI-XA-VINH-CHAU' => 'Thị xã Vĩnh Châu',
			),
			'SON-LA' => array(
				'HUYEN-BAC-YEN' => 'Huyện Bắc Yên',
				'HUYEN-MAI-SON' => 'Huyện Mai Sơn',
				'HUYEN-MOC-CHAU' => 'Huyện Mộc Châu',
				'HUYEN-MUONG-LA' => 'Huyện Mường La',
				'HUYEN-PHU-YEN' => 'Huyện Phù Yên',
				'HUYEN-QUYNH-NHAI' => 'Huyện Quỳnh Nhai',
				'THANH-PHO-SON-LA' => 'Thành phố Sơn La',
				'HUYEN-SONG-MA' => 'Huyện Sông Mã',
				'HUYEN-SOP-COP' => 'Huyện Sốp Cộp',
				'HUYEN-THUAN-CHAU' => 'Huyện Thuận Châu',
				'HUYEN-VAN-HO' => 'Huyện Vân Hồ',
				'HUYEN-YEN-CHAU' => 'Huyện Yên Châu',
			),
			'TAY-NINH' => array(
				'HUYEN-BEN-CAU' => 'Huyện Bến Cầu',
				'HUYEN-CHAU-THANH' => 'Huyện Châu Thành',
				'HUYEN-DUONG-MINH-CHAU' => 'Huyện Dương Minh Châu',
				'HUYEN-GO-DAU' => 'Huyện Gò Dầu',
				'HUYEN-HOA-THANH' => 'Huyện Hòa Thành',
				'HUYEN-TAN-BIEN' => 'Huyện Tân Biên',
				'HUYEN-TAN-CHAU' => 'Huyện Tân Châu',
				'THANH-PHO-TAY-NINH' => 'Thành phố Tây Ninh',
				'HUYEN-TRANG-BANG' => 'Huyện Trảng Bàng',
			),
			'THAI-BINH' => array(
				'HUYEN-DONG-HUNG' => 'Huyện Đông Hưng',
				'HUYEN-HUNG-HA' => 'Huyện Hưng Hà',
				'HUYEN-KIEN-XUONG' => 'Huyện Kiến Xương',
				'HUYEN-QUYNH-PHU' => 'Huyện Quỳnh Phụ',
				'THANH-PHO-THAI-BINH' => 'Thành phố Thái Bình',
				'HUYEN-THAI-THUY' => 'Huyện Thái Thụy',
				'HUYEN-TIEN-HAI' => 'Huyện Tiền Hải',
				'HUYEN-VU-THU' => 'Huyện Vũ Thư',
			),
			'THAI-NGUYEN' => array(
				'HUYEN-DAI-TU' => 'Huyện Đại Từ',
				'HUYEN-DINH-HOA' => 'Huyện Định Hóa',
				'HUYEN-DONG-HY' => 'Huyện Đồng Hỷ',
				'THI-XA-PHO-YEN' => 'Thị xã Phổ Yên',
				'HUYEN-PHU-BINH' => 'Huyện Phú Bình',
				'HUYEN-PHU-LUONG' => 'Huyện Phú Lương',
				'THANH-PHO-SONG-CONG' => 'Thành phố Sông Công',
				'THANH-PHO-THAI-NGUYEN' => 'Thành phố Thái Nguyên',
				'HUYEN-VO-NHAI' => 'Huyện Võ Nhai',
			),
			'THANH-HOA' => array(
				'HUYEN-BA-THUOC' => 'Huyện Bá Thước',
				'THI-XA-BIM-SON' => 'Thị xã Bỉm Sơn',
				'HUYEN-CAM-THUY' => 'Huyện Cẩm Thủy',
				'HUYEN-DONG-SON' => 'Huyện Đông Sơn',
				'HUYEN-HA-TRUNG' => 'Huyện Hà Trung',
				'HUYEN-HAU-LOC' => 'Huyện Hậu Lộc',
				'HUYEN-HOANG-HOA' => 'Huyện Hoằng Hóa',
				'HUYEN-LANG-CHANH' => 'Huyện Lang Chánh',
				'HUYEN-MUONG-LAT' => 'Huyện Mường Lát',
				'HUYEN-NGA-SON' => 'Huyện Nga Sơn',
				'HUYEN-NGOC-LAC' => 'Huyện Ngọc Lặc',
				'HUYEN-NHU-THANH' => 'Huyện Như Thanh',
				'HUYEN-NHU-XUAN' => 'Huyện Như Xuân',
				'HUYEN-NONG-CONG' => 'Huyện Nông Cống',
				'HUYEN-QUAN-HOA' => 'Huyện Quan Hóa',
				'HUYEN-QUAN-SON' => 'Huyện Quan Sơn',
				'HUYEN-QUANG-XUONG' => 'Huyện Quảng Xương',
				'THANH-PHO-SAM-SON' => 'Thành phố Sầm Sơn',
				'HUYEN-THACH-THANH' => 'Huyện Thạch Thành',
				'THANH-PHO-THANH-HOA' => 'Thành phố Thanh Hóa',
				'HUYEN-THIEU-HOA' => 'Huyện Thiệu Hóa',
				'HUYEN-THO-XUAN' => 'Huyện Thọ Xuân',
				'HUYEN-THUONG-XUAN' => 'Huyện Thường Xuân',
				'HUYEN-TINH-GIA' => 'Huyện Tĩnh Gia',
				'HUYEN-TRIEU-SON' => 'Huyện Triệu Sơn',
				'HUYEN-VINH-LOC' => 'Huyện Vĩnh Lộc',
				'HUYEN-YEN-DINH' => 'Huyện Yên Định',
			),
			'THUA-THIEN-HUE' => array(
				'HUYEN-A-LUOI' => 'Huyện A Lưới',
				'THANH-PHO-HUE' => 'Thành phố Huế',
				'THI-XA-HUONG-THUY' => 'Thị xã Hương Thủy',
				'THI-XA-HUONG-TRA' => 'Thị xã Hương Trà',
				'HUYEN-NAM-DONG' => 'Huyện Nam Đông',
				'HUYEN-PHONG-DIEN' => 'Huyện Phong Điền',
				'HUYEN-PHU-LOC' => 'Huyện Phú Lộc',
				'HUYEN-PHU-VANG' => 'Huyện Phú Vang',
				'HUYEN-QUANG-DIEN' => 'Huyện Quảng Điền',
			),
			'TIEN-GIANG' => array(
				'HUYEN-CAI-BE' => 'Huyện Cái Bè',
				'THI-XA-CAI-LAY' => 'Thị xã Cai Lậy',
				'HUYEN-CAI-LAY' => 'Huyện Cai Lậy',
				'HUYEN-CHAU-THANH' => 'Huyện Châu Thành',
				'HUYEN-CHO-GAO' => 'Huyện Chợ Gạo',
				'THI-XA-GO-CONG' => 'Thị xã Gò Công',
				'HUYEN-GO-CONG-DONG' => 'Huyện Gò Công Đông',
				'HUYEN-GO-CONG-TAY' => 'Huyện Gò Công Tây',
				'THANH-PHO-MY-THO' => 'Thành phố Mỹ Tho',
				'HUYEN-TAN-PHU-DONG' => 'Huyện Tân Phú Đông',
				'HUYEN-TAN-PHUOC' => 'Huyện Tân Phước',
			),
			'TRA-VINH' => array(
				'HUYEN-CANG-LONG' => 'Huyện Càng Long',
				'HUYEN-CAU-KE' => 'Huyện Cầu Kè',
				'HUYEN-CAU-NGANG' => 'Huyện Cầu Ngang',
				'HUYEN-CHAU-THANH' => 'Huyện Châu Thành',
				'HUYEN-DUYEN-HAI' => 'Huyện Duyên Hải',
				'THI-XA-DUYEN-HAI' => 'Thị xã Duyên Hải',
				'HUYEN-TIEU-CAN' => 'Huyện Tiểu Cần',
				'HUYEN-TRA-CU' => 'Huyện Trà Cú',
				'THANH-PHO-TRA-VINH' => 'Thành phố Trà Vinh',
			),
			'TUYEN-QUANG' => array(
				'HUYEN-CHIEM-HOA' => 'Huyện Chiêm Hóa',
				'HUYEN-HAM-YEN' => 'Huyện Hàm Yên',
				'HUYEN-LAM-BINH' => 'Huyện Lâm Bình',
				'HUYEN-NA-HANG' => 'Huyện Na Hang',
				'HUYEN-SON-DUONG' => 'Huyện Sơn Dương',
				'THANH-PHO-TUYEN-QUANG' => 'Thành phố Tuyên Quang',
				'HUYEN-YEN-SON' => 'Huyện Yên Sơn',
			),
			'VINH-LONG' => array(
				'HUYEN-VUNG-LIEM' => 'Huyện Vũng Liêm',
				'THI-XA-BINH-MINH' => 'Thị xã Bình Minh',
				'HUYEN-BINH-TAN' => 'Huyện Bình Tân',
				'HUYEN-LONG-HO' => 'Huyện Long Hồ',
				'HUYEN-MANG-THIT' => 'Huyện Mang Thít',
				'HUYEN-TAM-BINH' => 'Huyện Tam Bình',
				'HUYEN-TRA-ON' => 'Huyện Trà Ôn',
				'THANH-PHO-VINH-LONG' => 'Thành phố Vĩnh Long',
			),
			'VINH-PHUC' => array(
				'HUYEN-BINH-XUYEN' => 'Huyện Bình Xuyên',
				'HUYEN-LAP-THACH' => 'Huyện Lập Thạch',
				'THANH-PHO-PHUC-YEN' => 'Thành phố Phúc Yên',
				'HUYEN-SONG-LO' => 'Huyện Sông Lô',
				'HUYEN-TAM-DAO' => 'Huyện Tam Đảo',
				'HUYEN-TAM-DUONG' => 'Huyện Tam Dương',
				'HUYEN-VINH-TUONG' => 'Huyện Vĩnh Tường',
				'THANH-PHO-VINH-YEN' => 'Thành phố Vĩnh Yên',
				'HUYEN-YEN-LAC' => 'Huyện Yên Lạc',
			),
			'YEN-BAI' => array(
				'HUYEN-LUC-YEN' => 'Huyện Lục Yên',
				'HUYEN-MU-CANG-CHAI' => 'Huyện Mù Căng Chải',
				'THI-XA-NGHIA-LO' => 'Thị xã Nghĩa Lộ',
				'HUYEN-TRAM-TAU' => 'Huyện Trạm Tấu',
				'HUYEN-TRAN-YEN' => 'Huyện Trấn Yên',
				'HUYEN-VAN-CHAN' => 'Huyện Văn Chấn',
				'HUYEN-VAN-YEN' => 'Huyện Văn Yên',
				'THANH-PHO-YEN-BAI' => 'Thành phố Yên Bái',
				'HUYEN-YEN-BINH' => 'Huyện Yên Bình',
			)
		);
	}

	public function get_vn_state($state_key){
		$state = explode('--',$state_key);
		$list_provinces = $this->list_VN_provinces();
		$list_cities = $this->list_VN_cities();
		$district = $list_cities[$state[0]];
		if (!isset($list_provinces[$state[0]])) return false;
		if (!isset($district[$state[1]])) return false;
		return [
			'province' => $list_provinces[$state[0]],
			'district' => $district[$state[1]]
		];
	}

}
new Provinces();